### ISSUE TITLE
Build fails on windows

### ISSUE THREAD

**Issue by tugberkugurlu** [swagger-api/swagger-ui#1032]
ran `npm install` and `gulp`. Getting this:

```
[14:37:59] Using gulpfile c:\dev\swagger-ui\gulpfile.js
[14:37:59] Starting 'clean'...
[14:37:59] Finished 'clean' after 12 ms
[14:37:59] Starting 'dist'...
[14:37:59] Starting 'less'...
c:\dev\swagger-ui\node_modules\gulp-less\index.js:68
    }).done(undefined, cb);
       ^
TypeError: undefined is not a function
  at DestroyableTransform._transform (c:\dev\swagger-ui\node_modules\gulp-less\index.js:68:8)
  at DestroyableTransform.Transform._read (c:\dev\swagger-ui\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (c:\dev\swagger-ui\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:172:12)
  at doWrite (c:\dev\swagger-ui\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:237:10)
  at writeOrBuffer (c:\dev\swagger-ui\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (c:\dev\swagger-ui\node_modules\gulp-less\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:194:11)
  at write (c:\dev\swagger-ui\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
...
...
```

**Comment by mohsen1** [comment]
What version of Node (or iojs) are you using?

**Comment by mohsen1** [comment]
Probably related: https://github.com/plus3network/gulp-less/issues/140 (Native promises don't have `.done` method)

**Comment by webron** [comment]
@thadudexx - anything?

**Comment by webron** [comment]
Closing for lack of response. Please reopen if needed.
