### ISSUE TITLE
Gulp Event-Stream Issue

### ISSUE THREAD

**Issue by SwagUX** [swagger-api/swagger-ui#1746]
module.js:338
    throw err;
          ^
Error: Cannot find module 'event-stream'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\VNXB48\swagger-ui-master\gulpfile.js:4:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

When I run any Gulp command, I am getting the error above in my terminal.

**Comment by ponelat** [comment]
Please confirm you've installed all dependencies... `npm install`

**Comment by SwagUX** [comment]
yep that was the issue

**Comment by ponelat** [comment]
Awesome, closing the issue..
