### ISSUE TITLE
Swagger App crash if optional FILE is not sended

### ISSUE THREAD

**Issue by oliverhr** [swagger-api/swagger-ui#1818]
Defined route on swagger.yaml:
```
...
/avatar:
    x-swagger-router-controller: profile
    post:
      description: Upload user profile image
      operationId: avatar
      consumes:
        - multipart/form-data

      parameters:
        - name: alttext
          in: query
          type: string
          required: false

        - name: image
          in: formData
          type: file
          required: false

      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/SuccessResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
...
```

If you check on Swagger UI without sending a file, the application breaks.

Logs:
```

{
  alttext:
   { path: [ 'paths', '/video', 'post', 'parameters', '0' ],
     schema: { name: 'alttext', in: 'query', type: 'string', required: false },
     originalValue: 'Alternative Text to display',
     value: 'Alternative Text to display' },
  image:
   { path: [ 'paths', '/video', 'post', 'parameters', '1' ],
     schema: { name: 'image', in: 'formData', required: false, type: 'file' },
     originalValue: undefined,
     value: undefined } 
}

/.../node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:43
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /.../node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:43:36
    at /.../node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/async/lib/async.js:358:17
    at onFinish (/.../node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/multer/index.js:211:16)
    at Busboy.<anonymous> (/.../node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/multer/index.js:188:9)
    at emitNone (events.js:73:20)
    at Busboy.emit (events.js:167:7)
    at Busboy.emit (/.../node_modules/swagger-express-mw/node_modules/swagger-node-runner/node_modules/swagger-tools/node_modules/multer/node_modules/busboy/lib/main.js:31:35)
    at finishMaybe (_stream_writable.js:469:14)
    at afterWrite (_stream_writable.js:348:3)
    at nextTickCallbackWithManyArgs (node.js:477:18)
```

- Tested with Curl, Postman and Swagger UI.
- This just happen via Swagger UI.

**Comment by oliverhr** [comment]
Is the same o related to: https://github.com/swagger-api/swagger-ui/issues/1619

**Comment by gcoupelant** [comment]
+1

**Comment by fehguy** [comment]
This has been fixed
