### ISSUE TITLE
Handlebars is not defined

### ISSUE THREAD

**Issue by Siddeshgad** [swagger-api/swagger-ui#1965]
Handlebars is not defined
  at Object.<anonymous> (.../node_modules/swagger-ui/dist/swagger-ui.js:9:57)
  at Object.<anonymous> (.../node_modules/swagger-ui/dist/swagger-ui.js:26330:7)

This is the error message which I got when I tried importing swagger-ui package.

I tried installing and including Handlebars package before swagger_ui but it did not help.

Can you please provide solution to this problem?

**Comment by rmharrison** [comment]
Same issue. Tried with both node 4.5.0 and 6.5.0 (swagger-ui@2.2.2 node_modules/swagger-ui).
```node
> swaggerUI = require('swagger-ui')
ReferenceError: Handlebars is not defined
    at .. node_modules/swagger-ui/dist/swagger-ui.js:9:18
    at Object.<anonymous> (.. node_modules/swagger-ui/dist/swagger-ui.js:773:3)
    at Object.<anonymous> (.. node_modules/swagger-ui/dist/swagger-ui.js:24758:7)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at repl:1:13
```

**Comment by fehguy** [comment]
You'll have to require some packages to get it to work.  Please take a look at the [index.html](https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html)
