### ISSUE TITLE
Failed to build tag v2.1.8-M1

### ISSUE THREAD

**Issue by alivesubstance** [swagger-api/swagger-ui#2124]
Hi

I'm trying to build tag v2.1.8-M1 as described in the manual. The `npm install` works correctly but `gulp(or npm run build)` throw an exception. The exception can be find below. Can you please suggest what is wrong? 

dmirian@dmirian-ubuntu:~/code/swagger-ui$ npm run build

swagger-ui@2.1.8-M1 build /home/dmirian/code/swagger-ui
./node_modules/gulp/bin/gulp.js;

[14:20:32] Using gulpfile ~/code/swagger-ui/gulpfile.js
[14:20:32] Starting 'clean'...
[14:20:32] Finished 'clean' after 50 ms
[14:20:32] Starting 'dist'...
[14:20:32] Starting 'less'...
/home/dmirian/code/swagger-ui/node_modules/gulp-less/index.js:68
    }).done(undefined, cb);
       ^

TypeError: less.render(...).then(...).catch(...).done is not a function
  at DestroyableTransform._transform (/home/dmirian/code/swagger-ui/node_modules/gulp-less/index.js:68:8)
  at DestroyableTransform.Transform._read (/home/dmirian/code/swagger-ui/node_modules/gulp-less/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/home/dmirian/code/swagger-ui/node_modules/gulp-less/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/home/dmirian/code/swagger-ui/node_modules/gulp-less/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/home/dmirian/code/swagger-ui/node_modules/gulp-less/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/home/dmirian/code/swagger-ui/node_modules/gulp-less/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:80:13)
  at DestroyableTransform.emit (events.js:179:7)
  at emitReadable_ (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at DestroyableTransform.noop [as _transform] (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/through2/through2.js:26:3)
  at DestroyableTransform.Transform._read (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at emitNone (events.js:80:13)
  at DestroyableTransform.emit (events.js:179:7)
  at emitReadable_ (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at afterTransform (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:101:12)
  at TransformState.afterTransform (/home/dmirian/code/swagger-ui/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_transform.js:79:12)
  at /home/dmirian/code/swagger-ui/node_modules/vinyl-fs/lib/src/getContents/bufferFile.js:12:5
  at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:404:3)

npm ERR! Linux 3.13.0-73-generic
npm ERR! argv "/usr/local/bin/node" "/home/dmirian/.npm-packages/bin/npm" "run" "build"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.7
npm ERR! code ELIFECYCLE
npm ERR! swagger-ui@2.1.8-M1 build: `./node_modules/gulp/bin/gulp.js;`
npm ERR! Exit status 1

**Comment by fehguy** [comment]
Please consider using master.  The *.M1 / *.M2 builds are extremely old.

**Comment by alivesubstance** [comment]
Oh... thanks.
