### ISSUE TITLE
Handlebars not defined

### ISSUE THREAD

**Issue by ORESoftware** [swagger-api/swagger-ui#2239]
Got this issue:

```
/Users/Olegzandr/.nvm/versions/node/v6.2.2/lib/node_modules/swagger-ui/dist/swagger-ui.js:9
this["Handlebars"]["templates"]["apikey_button_view"] = Handlebars.template({"compiler":[6,">= 2.0.0-beta.1"],"main":function(depth0,helpers,partials,data) {
                                                        ^

ReferenceError: Handlebars is not defined
    at Object.<anonymous> (/Users/Olegzandr/.nvm/versions/node/v6.2.2/lib/node_modules/swagger-ui/dist/swagger-ui.js:9:57)
    at Object.<anonymous> (/Users/Olegzandr/.nvm/versions/node/v6.2.2/lib/node_modules/swagger-ui/dist/swagger-ui.js:26330:7)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

.json file looks like this:

``` json
{
  "basePath": "/accounts/v1beta2",
  "definitions": {
    "AssertionSignaturePayload": {
      "properties": {
        "messaging": {
          "type": "string"
        },
        "platform": {
          "type": "string"
        },
        "userdata": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "AuthTicket": {
      "properties": {
        "active": {
          "type": "boolean"
        },
        "admin": {
          "type": "boolean"
        },
        "enroll": {
          "type": "boolean"
        },
        "key": {
          "type": "string"
        },
        "signatures": {
          "$ref": "#/definitions/AssertionSignaturePayload"
        }
      },
      "type": "object"
    }
  },
  "host": "moover-co.appspot.com",
  "info": {
    "contact": {
      "name": "Moover, Inc.",
      "url": "https://moover.co"
    },
    "description": "Provides account management and provisioning services.",
    "title": "Accounts API",
    "version": "v1beta2",
    "x-serviceName": "accounts"
  },
  "parameters": {
    "alt": {
      "default": "json",
      "description": "Data format for the response.",
      "enum": [
        "json"
      ],
      "in": "query",
      "name": "alt",
      "type": "string"
    },
    "fields": {
      "description": "Selector specifying which fields to include in a partial response.",
      "in": "query",
      "name": "fields",
      "type": "string"
    },
    "key": {
      "description": "API key. Your API key identifies your project and provides you with API access, quota, and reports. Required unless you provide an OAuth 2.0 token.",
      "in": "query",
      "name": "key",
      "type": "string"
    },
    "oauth_token": {
      "description": "OAuth 2.0 token for the current user.",
      "in": "query",
      "name": "oauth_token",
      "type": "string"
    },
    "prettyPrint": {
      "default": true,
      "description": "Returns response with indentations and line breaks.",
      "in": "query",
      "name": "prettyPrint",
      "type": "boolean"
    },
    "quotaUser": {
      "description": "Available to use for quota purposes for server-side applications. Can be any arbitrary string assigned to a user, but should not exceed 40 characters. Overrides userIp if both are provided.",
      "in": "query",
      "name": "quotaUser",
      "type": "string"
    },
    "userIp": {
      "description": "IP address of the site where the request originates. Use this if you want to enforce per-user limits.",
      "in": "query",
      "name": "userIp",
      "type": "string"
    }
  },
  "paths": {
    "/account": {
      "get": {
        "operationId": "accounts.validate",
        "parameters": [
          {
            "in": "query",
            "name": "account",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "device",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "identity",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "token",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "nonce",
            "type": "string"
          },
          {
            "enum": [
              "FACEBOOK",
              "GOOGLE"
            ],
            "in": "query",
            "name": "provider",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "$ref": "#/definitions/AuthTicket"
            }
          }
        },
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/plus.me"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/userinfo.email"
            ]
          }
        ]
      },
      "parameters": [
        {
          "$ref": "#/parameters/alt"
        },
        {
          "$ref": "#/parameters/fields"
        },
        {
          "$ref": "#/parameters/key"
        },
        {
          "$ref": "#/parameters/oauth_token"
        },
        {
          "$ref": "#/parameters/prettyPrint"
        },
        {
          "$ref": "#/parameters/quotaUser"
        },
        {
          "$ref": "#/parameters/userIp"
        }
      ],
      "post": {
        "operationId": "accounts.resolve",
        "parameters": [
          {
            "in": "query",
            "name": "device",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "token",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "nonce",
            "type": "string"
          },
          {
            "enum": [
              "FACEBOOK",
              "GOOGLE"
            ],
            "in": "query",
            "name": "provider",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "$ref": "#/definitions/AuthTicket"
            }
          }
        },
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/plus.me"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/userinfo.email"
            ]
          }
        ]
      }
    },
    "/confirm": {
      "parameters": [
        {
          "$ref": "#/parameters/alt"
        },
        {
          "$ref": "#/parameters/fields"
        },
        {
          "$ref": "#/parameters/key"
        },
        {
          "$ref": "#/parameters/oauth_token"
        },
        {
          "$ref": "#/parameters/prettyPrint"
        },
        {
          "$ref": "#/parameters/quotaUser"
        },
        {
          "$ref": "#/parameters/userIp"
        }
      ],
      "post": {
        "operationId": "accounts.confirm",
        "parameters": [
          {
            "in": "query",
            "name": "code",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/plus.me"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/userinfo.email"
            ]
          }
        ]
      }
    },
    "/verify": {
      "parameters": [
        {
          "$ref": "#/parameters/alt"
        },
        {
          "$ref": "#/parameters/fields"
        },
        {
          "$ref": "#/parameters/key"
        },
        {
          "$ref": "#/parameters/oauth_token"
        },
        {
          "$ref": "#/parameters/prettyPrint"
        },
        {
          "$ref": "#/parameters/quotaUser"
        },
        {
          "$ref": "#/parameters/userIp"
        }
      ],
      "post": {
        "operationId": "accounts.verify",
        "parameters": [
          {
            "in": "query",
            "name": "email",
            "required": true,
            "type": "string"
          },
          {
            "in": "query",
            "name": "number",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response"
          }
        },
        "security": [
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/plus.me"
            ]
          },
          {
            "Oauth2": [
              "https://www.googleapis.com/auth/userinfo.email"
            ]
          }
        ]
      }
    }
  },
  "schemes": [
    "https"
  ],
  "securityDefinitions": {
    "Oauth2": {
      "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
      "description": "Oauth 2.0 authentication",
      "flow": "implicit",
      "scopes": {
        "https://www.googleapis.com/auth/plus.me": "Know who you are on Google",
        "https://www.googleapis.com/auth/userinfo.email": "View your email address"
      },
      "type": "oauth2"
    }
  },
  "swagger": "2.0",
  "tags": []
}
```

**Comment by fehguy** [comment]
What are you trying to do?  If you're looking to build the distribution, run gulp.
