### ISSUE TITLE
Swagger UI Content Type is multipart/form-data when type specified in spec is x-www-form-url-encoded

### ISSUE THREAD

**Issue by jencodingatwork** [swagger-api/swagger-ui#2251]
I'm using the latest swagger-ui (I pulled down the master on June 30,2016). When I try to upload a file and a string and a file with the content type x-www-form-url-encoded set in the spec the request still shows the content type as multipart/form-data.

![request](https://cloud.githubusercontent.com/assets/18533582/16494283/bb8d90d0-3eb6-11e6-8c7b-e959b6d1a42a.JPG)

Here is the spec for reproducing the issue:
[plugin.txt](https://github.com/swagger-api/swagger-ui/files/341773/plugin.txt)

You can also view some of the code on my github page: https://github.com/jencodingatwork/PluginAPI

**Comment by fehguy** [comment]
You can't upload files with x-www-form-url-encoded, only mulitipart is supported

**Comment by jencodingatwork** [comment]
Doesn't this part of the specification say it is supported?

> Form - Used to describe the payload of an HTTP request when either application/x-www-form-urlencoded, multipart/form-data or both are used as the content type of the request (in Swagger's definition, the consumes property of an operation). This is the only parameter type that can be used to send files, thus supporting the file type. Since form parameters are sent in the payload, they cannot be declared together with a body parameter for the same operation. Form parameters have a different format based on the content-type used (for further details, consult http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4):
> 
>     application/x-www-form-urlencoded - Similar to the format of Query parameters but as a payload. For example, foo=1&bar=swagger - both foo and bar are form parameters. This is normally used for simple parameters that are being transferred.
>     multipart/form-data - each parameter takes a section in the payload with an internal header. For example, for the header Content-Disposition: form-data; name="submit-name" the name of the parameter is submit-name. This type of form parameters is more commonly used for file transfers.

Either way, when I change the content type to multipart then I get this error: 

```
java.lang.IllegalStateException: The @FormParam is utilized when the content type of the request entity is not application/x-www-form-urlencoded
	at org.glassfish.jersey.server.internal.inject.FormParamValueFactoryProvider$FormParamValueFactory.ensureValidRequest(FormParamValueFactoryProvider.java:183) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.internal.inject.FormParamValueFactoryProvider$FormParamValueFactory.getForm(FormParamValueFactoryProvider.java:167) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.internal.inject.FormParamValueFactoryProvider$FormParamValueFactory.provide(FormParamValueFactoryProvider.java:118) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.provide(ParamValueFactoryWithSource.java:71) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:90) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:127) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) ~[jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471) ~[jersey-container-servlet-core-2.22.1.jar:na]
	... 45 common frames omitted
```

**Comment by fehguy** [comment]
That's a different issue, you are using the wrong annotations.  Use `@FormDataParam` instead of `@FormParam` for multipart.  Please open those issues in [swagger-core](http://github.com/swagger-api/swagger-core).

**Comment by jencodingatwork** [comment]
I'm confused am I opening an issue for x-www-form-urlencoded not being supported as it is stated in the specification or for @FormParam throwing an IllegalException error?

**Comment by fehguy** [comment]
I'm saying that swagger-ui supports file uploads _only_ with multipart/form-data.  Additionally, the stack trace that you are getting is because you changed your `@Consumes` to multipart, but you are using the wrong annotations

**Comment by jencodingatwork** [comment]
So Swagger supports both but the UI only supports multipart/form-data? Do you have plans to add in support for x-www-form-urlencoded to the UI in the future?

You are correct, when I updated the annotation for the json string to be @FormDataParam instead of @FormParam and changed the @consumes back to multip-part the error went away.
