### ISSUE TITLE
Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by kabo** [swagger-api/swagger-ui#2788]
I followed the [usage instructions](http://swagger.io/docs/#usage-34) and when I opened index.html I got a blank page, and the console said:

```
Uncaught Error: only one instance of babel-polyfill is allowed            swagger-ui-standalone-preset.js:1 
```
Followed by
```
Uncaught ReferenceError: SwaggerUIStandalonePreset is not defined             index.html:81
```

Tested in both Firefox and Chromium.

**Comment by kabo** [comment]
Ah, the docs I linked to said

> Step 3: Run the dist/index.html file on a browser or place the dist folder inside your server.

But if I use `public/index.html` instead it works fine :)

**Comment by anatolym** [comment]
Same here.
> @kabo: But if I use public/index.html instead it works fine :)

This doesn't work since `public/index.html` was removed in 997a31c.

**Comment by kabo** [comment]
Ah, you're right, I'm on f653591 where it works.

**Comment by quanvuong** [comment]
You need to rebuild the dist then it will work `npm i && npm run build` did the trick for me

**Comment by webron** [comment]
Apologies for the confusion everyone, we're in the process of updating the distribution, the docs, and everything around, so some things may be confusing. It'll take a bit to stabilize, but we'll get there soon.

**Comment by webron** [comment]
This should be covered now.

**Comment by nicgirault** [comment]
I still have the problem with swagger-ui-dist

```
> babel-node src/index.js --presets es2015,stage-2

/home/nicolas/projects/lalilo-api/node_modules/swagger-ui-dist/swagger-ui-bundle.js:1
(function (exports, require, module, __filename, __dirname) { !function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.SwaggerUIBundle=t():e.SwaggerUIBundle=t()}(this,function(){return function(e){function t(r){if(n[r])return n[r].exports;var i=n[r]={exports:{},id:r,loaded:!1};return e[r].call(i.exports,i,i.exports,t),i.loaded=!0,i.exports}var n={};return t.m=e,t.c=n,t.p="/dist",t(0)}(function(e){for(var t in e)if(Object.prototype.hasOwnProperty.call(e,t))switch(typeof e[t]){case"function":break;case"object":e[t]=function(t){var n=t.slice(1),r=e[t[0]];return function(e,t,i){r.apply(this,[e,t,i].concat(n))}}(e[t]);break;default:e[t]=e[e[t]]}return e}([function(e,t,n){n(1),e.exports=n(297)},function(e,t,n){(function(e){"use strict";function t(e,t,n){e[t]||Object[r](e,t,{writable:!0,configurable:!0,value:n})}if(n(2),

Error: only one instance of babel-polyfill is allowed
    at Object.<anonymous> (/home/nicolas/projects/lalilo-api/node_modules/swagger-ui-dist/webpack:/swagger-ui-bundle.js:1:1)
    at Object.<anonymous> (/home/nicolas/projects/lalilo-api/node_modules/swagger-ui-dist/webpack:/swagger-ui-bundle.js:1:1)
    at t (/home/nicolas/projects/lalilo-api/node_modules/swagger-ui-dist/webpack:/swagger-ui-bundle.js:1:1)
    at Object.e.(anonymous function).Object.(anonymous function).writable (/home/nicolas/projects/lalilo-api/node_modules/swagger-ui-dist/webpack:/swagger-ui-bundle.js:1:1)
    at t (/home/nicolas/projects/lalilo-api/node_modules/swagger-ui-dist/webpack:/swagger-ui-bundle.js:1:1)
    at /home/nicolas/projects/lalilo-api/node_modules/swagger-ui-dist/webpack:/swagger-ui-bundle.js:1:1
    at /home/nicolas/projects/lalilo-api/node_modules/swagger-ui-dist/webpack:/swagger-ui-bundle.js:1:1
    at n.(anonymous function).exports (/home/nicolas/projects/lalilo-api/node_modules/swagger-ui-dist/webpack:/swagger-ui-bundle.js:1:1)
    at Object.<anonymous> (/home/nicolas/projects/lalilo-api/node_modules/swagger-ui-dist/webpack:/swagger-ui-bundle.js:1:1)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (/home/nicolas/projects/lalilo-api/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```
