### ISSUE TITLE
Can't read from file 

### ISSUE THREAD

**Issue by anhchienhoang** [swagger-api/swagger-ui#2827]
I got this error when testing with the master repository:

```
https://online.swagger.io/validator
swagger-ui-bundle.js:79963 Uncaught (in promise) TypeError: Cannot read property 'bind' of undefined
    at m (swagger-ui-bundle.js:79963)
    at p._constructComponentWithoutOwner (swagger-ui-bundle.js:49806)
    at p._constructComponent (swagger-ui-bundle.js:49806)
    at p.mountComponent (swagger-ui-bundle.js:49806)
    at Object.mountComponent (swagger-ui-bundle.js:42109)
    at d.mountChildren (swagger-ui-bundle.js:49806)
    at d._createInitialChildren (swagger-ui-bundle.js:45573)
    at d.mountComponent (swagger-ui-bundle.js:45573)
    at Object.mountComponent (swagger-ui-bundle.js:42109)
    at d.mountChildren (swagger-ui-bundle.js:49806)
```

I'm using file reference in the swagger like this
```
paths:
  /users/{id}:
    $ref: 'operations/users.yaml#GetUser'
```

It displays the header and Loading... and red Error block. When clicking on that error link I got this response:
```
{
"schemaValidationMessages": [
{
"level": "error",
"message": "Can't read from file http://localhost:8061/swagger/swagger.yaml"
}
]
}
```
Ps: it worked well before.
Also tested with docker images and doesn't work from v3.0.0. It works well with v2.2.9

**Comment by webron** [comment]
@bodnia can you please look into that? Following the configuration to disable the validator, just like it's disabled for embedded specs by default, it should be disabled by default to localhost (the online validator will never be able to access those).

**Comment by bodnia** [comment]
@anhchienhoang disabled validation for spec hosted in localhost in latest `master`, please try this and confirm if this is working

**Comment by anhchienhoang** [comment]
@bodnia I just tried and got this error:
```
$ref: "./operations/devices.yaml#Auth"
basePath
:
undefined
fullPath
:
Array[3]
level
:
"error"
line
:
17
message
:
"Could not resolve reference because of: Tried to resolve a relative URL, without having a basePath. path: './operations/devices.yaml' basePath: 'undefined'"
originalError
:
n
path
:
"paths./devices/auth.$ref"
pointer
:
"Auth"
source
:
"resolver"
stack
:
"JSONRefError↵    at o (http://localhost:8062/swagger-ui-bundle.js:73:21460)↵    at Object.plugin (http://localhost:8062/swagger-ui-bundle.js:73:23746)↵    at http://localhost:8062/swagger-ui-bundle.js:73:13858↵    at i (http://localhost:8062/swagger-ui-bundle.js:2:27152)↵    at Generator._invoke (http://localhost:8062/swagger-ui-bundle.js:2:28248)↵    at Generator.e.(anonymous function) [as next] (http://localhost:8062/swagger-ui-bundle.js:2:27331)↵    at i (http://localhost:8062/swagger-ui-bundle.js:2:27152)↵    at p (http://localhost:8062/swagger-ui-bundle.js:2:28680)↵    at Generator._invoke (http://localhost:8062/swagger-ui-bundle.js:2:28025)↵    at Generator.e.(anonymous function) [as next] (http://localhost:8062/swagger-ui-bundle.js:2:27331)"
type
:
"thrown"
```

**Comment by webron** [comment]
@anhchienhoang we have a few issues regarding resolving relative references, and dealing with no `host`, `schemes` or `basePath` defined. I'm hoping to get those resolved in the upcoming days.

**Comment by anhchienhoang** [comment]
Okay, I see. I can use the old version to work on. Thanks.

**Comment by webron** [comment]
Closing as fixed.

**Comment by anhchienhoang** [comment]
Confirmed that it works well. Thanks.
