### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by opichon** [swagger-api/swagger-ui#2845]
``` bash
$ npm run build

> swagger-ui@3.0.4 build /Users/olivier/projects/polifonic/api-docs
> npm run build-core && npm run build-bundle && npm run build-standalone


> swagger-ui@3.0.4 build-core /Users/olivier/projects/polifonic/api-docs
> webpack --config webpack-dist.config.js --colors

module.js:472
    throw err;
    ^

Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/olivier/projects/polifonic/api-docs/make-webpack-config.js:3:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "run" "build-core"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swagger-ui@3.0.4 build-core: `webpack --config webpack-dist.config.js --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-ui@3.0.4 build-core script 'webpack --config webpack-dist.config.js --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the swagger-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config webpack-dist.config.js --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs swagger-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls swagger-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/olivier/.npm/_logs/2017-04-04T05_42_03_692Z-debug.log

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swagger-ui@3.0.4 build: `npm run build-core && npm run build-bundle && npm run build-standalone`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-ui@3.0.4 build script 'npm run build-core && npm run build-bundle && npm run build-standalone'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the swagger-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-core && npm run build-bundle && npm run build-standalone
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs swagger-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls swagger-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/olivier/.npm/_logs/2017-04-04T05_42_03_753Z-debug.log
```

Log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/7.8.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.2.0
3 info using node@v7.8.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle swagger-ui@3.0.4~prebuild: swagger-ui@3.0.4
6 silly lifecycle swagger-ui@3.0.4~prebuild: no script for prebuild, continuing
7 info lifecycle swagger-ui@3.0.4~build: swagger-ui@3.0.4
8 verbose lifecycle swagger-ui@3.0.4~build: unsafe-perm in lifecycle true
9 verbose lifecycle swagger-ui@3.0.4~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/olivier/projects/polifonic/api-docs/node_modules/.bin:/Users/olivier/.composer/vendor/bin:/usr/local/sbin:/Users/olivier/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/node/7.8.0/bin
10 verbose lifecycle swagger-ui@3.0.4~build: CWD: /Users/olivier/projects/polifonic/api-docs
11 silly lifecycle swagger-ui@3.0.4~build: Args: [ '-c',
11 silly lifecycle   'npm run build-core && npm run build-bundle && npm run build-standalone' ]
12 silly lifecycle swagger-ui@3.0.4~build: Returned: code: 1  signal: null
13 info lifecycle swagger-ui@3.0.4~build: Failed to exec build script
14 verbose stack Error: swagger-ui@3.0.4 build: `npm run build-core && npm run build-bundle && npm run build-standalone`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid swagger-ui@3.0.4
16 verbose cwd /Users/olivier/projects/polifonic/api-docs
17 error Darwin 16.4.0
18 error argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v7.8.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error swagger-ui@3.0.4 build: `npm run build-core && npm run build-bundle && npm run build-standalone`
23 error Exit status 1
24 error Failed at the swagger-ui@3.0.4 build script 'npm run build-core && npm run build-bundle && npm run build-standalone'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the swagger-ui package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     npm run build-core && npm run build-bundle && npm run build-standalone
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs swagger-ui
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls swagger-ui
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

I do have the latest node and npm versions:

``` bash
$ node -v
v7.8.0
$ npm -v
4.2.0
```

**Comment by webron** [comment]
As the [Prerequisites](https://github.com/swagger-api/swagger-ui#prerequisites) say - you need Node 6.
