### ISSUE TITLE
Question: how to setup swagger-ui using webpack?

### ISSUE THREAD

**Issue by zdila** [swagger-api/swagger-ui#2849]
We install `swagger-ui` by `npm i swagger-ui`.

We use following code in the entry point:

```
import SwaggerUi, { plugins, presets } from 'swagger-ui';

SwaggerUi({
  dom_id: '#swaggerContainer',
  url: '/api/swagger.json',
  presets: [
    presets.apis
  ],
  plugins: [
    // plugins.SpecIndex,
    // plugins.LayoutIndex
  ],
  //layout: ''
});
```

With this we are getting white page with `No layout defined for "Layout"` text and nothing more. Is there anything else to be configured?

We are also getting following errors from Webpack:
```
[2] WARNING in ./src/swagger.js
[2] 
[2] /home/fred/superproject/src/swagger.js
[2]   1:21  warning  'plugins' is defined but never used  no-unused-vars
[2]   3:1   warning  Unexpected 'todo' comment            no-warning-comments
[2] 
[2] ✖ 2 problems (0 errors, 2 warnings)
[2] 
[2] 
[2] WARNING in ./~/yaml-js/lib/yaml.js
[2] require.extensions is not supported by webpack. Use a loader instead.
[2] 
[2] WARNING in ./~/yaml-js/lib/yaml.js
[2] require.extensions is not supported by webpack. Use a loader instead.
[2] 
[2] WARNING in ./~/yaml-js/lib/yaml.js
[2] require.extensions is not supported by webpack. Use a loader instead.
[2] 
[2] WARNING in ./~/yaml-js/lib/yaml.js
[2] Critical dependencies:
[2] 256:40-47 require function is used in a way in which dependencies cannot be statically extracted
[2]  @ ./~/yaml-js/lib/yaml.js 256:40-47
[2] 
[2] ERROR in ./~/yaml-js/lib/yaml.js
[2] Module not found: Error: Cannot resolve module 'fs' in /home/fred/superproject/node_modules/yaml-js/lib
[2] resolve module fs in /home/fred/superproject/node_modules/yaml-js/lib
[2]   looking for modules in /home/fred/superproject/node_modules
[2]     /home/fred/superproject/node_modules/fs doesn't exist (module as directory)
[2]     resolve 'file' fs in /home/fred/superproject/node_modules
[2]       resolve file
[2]         /home/fred/superproject/node_modules/fs doesn't exist
[2]         /home/fred/superproject/node_modules/fs.webpack.js doesn't exist
[2]         /home/fred/superproject/node_modules/fs.web.js doesn't exist
[2]         /home/fred/superproject/node_modules/fs.js doesn't exist
[2]         /home/fred/superproject/node_modules/fs.json doesn't exist
[2] [/home/fred/superproject/node_modules/fs]
[2] [/home/fred/superproject/node_modules/fs]
[2] [/home/fred/superproject/node_modules/fs.webpack.js]
[2] [/home/fred/superproject/node_modules/fs.web.js]
[2] [/home/fred/superproject/node_modules/fs.js]
[2] [/home/fred/superproject/node_modules/fs.json]
[2]  @ ./~/yaml-js/lib/yaml.js 257:9-22
[2] 
[2] ERROR in ./~/react-split-pane/index.js
[2] Module build failed: Error: Cannot find module 'babelify' from '/home/fred/superproject/node_modules/react-split-pane'
[2]     at /home/fred/superproject/node_modules/resolve/lib/async.js:46:31
[2]     at processDirs (/home/fred/superproject/node_modules/resolve/lib/async.js:177:39)
[2]     at ondir (/home/fred/superproject/node_modules/resolve/lib/async.js:192:13)
[2]     at load (/home/fred/superproject/node_modules/resolve/lib/async.js:77:43)
[2]     at onex (/home/fred/superproject/node_modules/resolve/lib/async.js:100:31)
[2]     at /home/fred/superproject/node_modules/resolve/lib/async.js:23:47
[2]     at FSReqWrap.oncomplete (fs.js:123:15)
[2]  @ ./~/swagger-ui/dist/swagger-ui.js 1:468-495 4:7898-7925
```
Command `npm i babelify` fixed babelify part but not yaml.

**Comment by shockey** [comment]
Hi @zdila! 

You can ignore the yaml-js messages- they're warnings. Feel free to open a PR over at `yaml-js` if the message bothers you 😄 

The `fs` issue is a yaml-js thing as well, you can see how we handle it here: https://github.com/swagger-api/swagger-ui/blob/master/make-webpack-config.js#L107

For the layout message- you do need to provide a layout to Swagger-UI. We have an example layout [here](https://github.com/swagger-api/swagger-ui/blob/master/src/standalone/layout.jsx). 

I'd be open to rewiring the way this works by moving that layout file into the core, and using it by default if the end user doesn't specify one. Let me know what you think about that. 

Today, you'll need to do the following:

- Create a layout component (example: https://github.com/swagger-api/swagger-ui/blob/master/src/standalone/layout.jsx)
- Give Swagger-UI a plugin that provides your layout component (example: https://github.com/swagger-api/swagger-ui/blob/master/src/standalone/index.js#L10)
- Refer to your layout component by name when you call Swagger-UI (example: https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html#L85)

**Comment by zdila** [comment]
Thanks @shockey, it works.

> I'd be open to rewiring the way this works by moving that layout file into the core, and using it by default if the end user doesn't specify one. Let me know what you think about that.

I agree. I would like just to do `npm i swagger-ui` and write only minimal JS to setup swagger UI without writing any layout component.

---

The problem I have now is that if I try to call my API from swagger-ui then it uses HTTP protocol instead of HTTPS. Our definition contains `"schemes": [ "https" ]` and also URL in `SwaggerUi({ url: ...` beginds with `https://`. Any advice?

**Comment by shockey** [comment]
@zdila, we're tracking the `schemes` issue here: https://github.com/swagger-api/swagger-ui/issues/2816#issuecomment-292278922

I've opened #2871 to track the possibility of moving the layout code into core.

Closing this as the original question is solved 🍻
