### ISSUE TITLE
Help with error: "Unknown plugin 'module-alias'"

### ISSUE THREAD

**Issue by JimSterling** [swagger-api/swagger-ui#3274]
I am getting the following error when running `npm run build`. I have tried it in v3.0.12, v3.0.14, and v3.0.15. I am using CentOS 7, and I can get the build to complete when I run it in the directory I have checked out the repo in. 

> ERROR in ./src/core/index.js
Module build failed: ReferenceError: Unknown plugin "module-alias" specified in "/var/www/swagger-ui/.babelrc" at 0, attempted to resolve relative to "/var/www/swagger-ui"
    at /var/www/swagger-ui/releases/v3.0.15/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/var/www/swagger-ui/releases/v3.0.15/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/var/www/swagger-ui/releases/v3.0.15/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/var/www/swagger-ui/releases/v3.0.15/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/var/www/swagger-ui/releases/v3.0.15/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/var/www/swagger-ui/releases/v3.0.15/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/var/www/swagger-ui/releases/v3.0.15/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/var/www/swagger-ui/releases/v3.0.15/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/var/www/swagger-ui/releases/v3.0.15/node_modules/babel-loader/lib/index.js:163:20)
 @ multi swagger-ui-bundle

**Comment by shockey** [comment]
Hey @JimSterling,

I just spun up a CentOS 7.3.1611 x64 machine and had some trouble reproducing this problem.

I ran:
- `git clone https://github.com/swagger-api/swagger-ui.git`
- `cd swagger-ui`
- `npm install`
- `npm run build`

and the build exited cleanly.

Please share with me the following info, so I can try to isolate what's going on:

- Your exact CentOS version
- Node.js version
- npm version
- the swagger-ui commit you're trying to build for

Lastly, you might try a fresh clone of Swagger-UI - your repository might be in a bad state somehow.

**Comment by JimSterling** [comment]
os: centos-release-7-3.1611.el7.centos.x86_64

node: v6.10.3

npm: 3.10.10

Swagger-ui version: 3.0.15

I can try to svn checkout the repo again. I had done that before, and I can get the build to pass when I npm install inside the tag location for v3.0.15, but I can't when I copy the 3.0.15 tag to my project directory

**Comment by shockey** [comment]
@JimSterling, that's interesting. Are you sure you're copying _all_ the files in the cloned directory? Bash `cp` doesn't always copy hidden files (files that start with a `.`), depending on how you do it.

**Comment by JimSterling** [comment]
That might have done it. But I downloded the zip of the master branch, and moved it over using winSCP, and it worked. So I think it might be the "." folders

**Comment by webron** [comment]
Great! Does this mean the issue can be closed? ;)
