### ISSUE TITLE
npm run build fails

### ISSUE THREAD

**Issue by GenaBitu** [swagger-api/swagger-ui#3733]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |  Bug
| Which Swagger/OpenAPI version?  |3.0.0
| Which Swagger-UI version?       | 3.3.1
| How did you install Swagger-UI? | git clone & git checkout
| Which browser & version?        |
| Which operating system?         | debian testing on x64

I cloned this repo, checked out tag 3.3.1 and ran `npm run build`. This is what I got:

```bash
> swagger-ui@3.3.1 build /home/user/swagger-ui
> npm run build-core && npm run build-bundle && npm run build-standalone


> swagger-ui@3.3.1 build-core /home/user/swagger-ui
> webpack --config webpack-dist.config.js --colors

/home/user/swagger-ui/webpack-dist.config.js:6
let rules = [
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (/home/user/swagger-ui/node_modules/webpack/bin/convert-argv.js:96:18)
    at /home/user/swagger-ui/node_modules/webpack/bin/convert-argv.js:109:17
    at Array.forEach (native)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swagger-ui@3.3.1 build-core: `webpack --config webpack-dist.config.js --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-ui@3.3.1 build-core script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-10-06T20_42_28_836Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swagger-ui@3.3.1 build: `npm run build-core && npm run build-bundle && npm run build-standalone`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the swagger-ui@3.3.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2017-10-06T20_42_28_859Z-debug.log
```
[2017-10-06T20_42_28_859Z-debug.log](https://github.com/swagger-api/swagger-ui/files/1363861/2017-10-06T20_42_28_859Z-debug.log)

**Comment by webron** [comment]
You're using node 4. Notice our build requirements state node 6.

**Comment by GenaBitu** [comment]
Oh, yes, didn't realize debian had outdated node... Is there a way to maybe add some meaningful error message when this happens?

**Comment by shockey** [comment]
Yeah, it'd be pretty easy to use `process.version` and `semver` to check the Node version, something like this in `make-webpack-config`:

```js
const semver = require('semver')

if (semver.lt(process.version, '6.0.0')) {
  console.warn('This command requires Node.js 6.0.0 or later')
  process.exit(1)
}
```

A PR would be appreciated :smile: 

As for Node.js versions - most folks use something like [`nvm`](https://github.com/creationix/nvm) to manage their Node.js versions, as it's much easier and up-to-date than traditional distro channels. Give it a try if you haven't already!

**Comment by shockey** [comment]
Closing due to inactivity. 

This is simply to keep our issue tracker clean - feel free to comment if there are any further thoughts or concerns, and we'll be happy to reopen this issue.

**Comment by feenr** [comment]
Where are these build requirements stated? CONTRIBUTING.md says "Install Node.js (4 or newer) and npm (3 or newer)."

**Comment by shockey** [comment]
@feenr, the correct requirements are in the `README.md`: https://github.com/swagger-api/swagger-ui/blob/master/README.md#prerequisites

Feel free to open a PR that corrects the error in `CONTRIBUTING.md` :smile:

**Comment by feenr** [comment]
Thanks for the very fast reply. I was just coming to update my comment.
