### ISSUE TITLE
Swagger-ui : ReferenceError : document is not defined

### ISSUE THREAD

**Issue by dlarr** [swagger-api/swagger-ui#4377]
| Q                               | A
| ------------------------------- | -------
| Bug or feature request?         |   Bug
| Which Swagger/OpenAPI version?  | 2.0
| Which Swagger-UI version?       | Tried 3.13.1 - 3.13.0 - 3.12.0 - 3.10.0 - 2.2.8
| How did you install Swagger-UI? | npm install swagger-ui /// npm install swagger-ui-dist
| Which browser & version?        | Firefox 59.0.1
| Which operating system?         | Windows 10

### Demonstration API definition

I don't understand what I have to tell here. I'll link the definition

```yaml
info:
  title: GESTIONNAIRE D'ORGANISATIONS
  version: 1.0.0
  description: Défintions des API délivrées par le gestionnaire d'organisations
host: 'localhost:3101'
basePath: /api/
produces:
  - application/json
swagger: '2.0'
paths:
  /organisation/:
    get:
      description: 'Récupère toutes les organisations, sans les données d''adresses, de media ou de relation'
      tags:
        - organisation
      produces:
        - application/json
      responses:
        '200':
          description: Toute les organisations
          schema:
            type: array
            items:
              $ref: '#/definitions/Organisation'
definitions:
  Organisation:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Identifiant unique technique
      dateDebut:
        type: string
        format: date-time
        description: Date début d\'entrée en service de l\'organisation
      dateFin:
        type: string
        format: date-time
        description: Date fin de service de l\'organisation
      perimTer:
        type: string
        description: Périmètre territorial
        enum:
          - National
          - Regional
          - Départemental
          - Local
      typeAssoAdmr:
        type: string
        description: Correspond à des statuts d\'association prédéfinis
        enum:
          - Asso Locale
          - Fédération Départementale
          - Comité Régional
          - Structure nationale
          - Autre Association Admr
          - Autre Admr
          - Non Admr Niveau Territorial
      nomOrg:
        type: string
        description: Nom de l\'organisation
      siren:
        type: integer
        description: SIREN de l\'organisation
      codape:
        type: integer
        description: Code APE de l\'organisation
      idFoncMedia:
        type: string
        description: ID fonctionnel des coordonnées médiatiques de l\'organisation
      idFoncAdresse:
        type: string
        description: ID fonctionnel de l\'adresse de l\'organisation
      deleted:
        type: boolean
        description: Determine wether this entity has been logically deleted
      organisations:
        type: array
        items:
          $ref: '#/definitions/Organisation'
    example:
      siren: 6
      deleted: true
      codape: 1
      dateDebut: '2000-01-23T04:56:07.000+00:00'
      idFoncAdresse: idFoncAdresse
      typeAssoAdmr: Asso Locale
      id: 0
      dateFin: '2000-01-23T04:56:07.000+00:00'
      perimTer: National
      idFoncMedia: idFoncMedia
      nomOrg: nomOrg
  Relation:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Identifiant unique technique
      lien:
        type: string
      id_organisationSource:
        type: integer
        format: int64
      id_organisationTarget:
        type: integer
        format: int64
      deleted:
        type: boolean
        description: Determine wether this entity has been logically deleted
    example:
      deleted: true
      lien: gere
      id: 0
      id_organisationSource: 6
      id_organisationTarget: 1
  Media:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Identifiant unique de l\'instance de coordonnées médiatiques
      idFonctionnel:
        type: string
        description: 'Identifiant fonctionnel de l\''instance de coordonnées médiatiques de la forme suivante : MED_[TRIGRAMME_TABLE_OBJ]_[ID_OBJ]. Example : MED_ORG_1, Note : l\''identifiant fonctionnel permet de voir à quelle entité est rattachée ce média'
      tel1:
        type: string
        description: Correspond au premier téléphone fixe
      tel2:
        type: string
        description: Correspond au deuxième téléphone fixe
      mobile1:
        type: string
        description: Correspond au premier téléphone mobile
      mobile2:
        type: string
        description: Correspond au deuxième téléphone mobile
      mail:
        type: string
        description: Correspond au mail de contact
      fax:
        type: string
        description: Correspond au fax
      siteWeb:
        type: string
        description: URL du site web de l\'entité
      dateDebutValidite:
        type: string
        format: date-time
        description: Date de début de validité de l\'instance de coordonées médiatiques
      dateFinValidite:
        type: string
        format: date-time
        description: Date de fin de validité de l\'instance de coordonées médiatiques
      dateInsertion:
        type: string
        format: date-time
        description: Date de création de l\'instance de coordonées médiatiques
      dateModification:
        type: string
        format: date-time
        description: Date de modification de l\'instance de coordonées médiatiques
      deleted:
        type: boolean
        description: Determine wether this entity has been logically deleted
    example:
      tel1: tel1
      tel2: tel2
      dateInsertion: '2000-01-23T04:56:07.000+00:00'
      dateDebutValidite: '2000-01-23T04:56:07.000+00:00'
      mail: mail
      idFonctionnel: idFonctionnel
      siteWeb: siteWeb
      dateModification: '2000-01-23T04:56:07.000+00:00'
      mobile1: mobile1
      deleted: true
      mobile2: mobile2
      id: 0
      fax: fax
      dateFinValidite: '2000-01-23T04:56:07.000+00:00'
  Adresse:
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Identifiant unique de l\'adresse
      idFonctionnel:
        type: string
        description: 'Identifiant fonctionnel de l\''adresse de la forme suivante : ADR_[TRIGRAMME_TABLE_OBJ]_[ID_OBJ]. Example : ADR_ORG_ID1'
      adressePro:
        type: boolean
        description: 'Defini s\''il s\''agit d\''une adresse pro ou non. Si 1, adressePro. Si 0, adresse particulier'
      civilite:
        type: string
        description: '[AFNOR LIGNE 1] - Uniquement pour adresse particulier : Civilité, titre ou qualité. Exemple: Monsieur, Madame, Docteur, Maitre, etc...'
      prenom:
        type: string
        description: '[AFNOR LIGNE 1] - Uniquement pour adresse particulier : Prénom du destinataire'
      nom:
        type: string
        description: '[AFNOR LIGNE 1] - Uniquement pour adresse particulier : Nom du destinataire'
      raisonSociale:
        type: string
        description: '[AFNOR LIGNE 1] - Uniquement pour adresse pro : Raison sociale ou dénomination de la société'
      complementAdresse1:
        type: string
        description: '[AFNOR LIGNE 2] - Pour adresse pro/particulière. Il s\''agit d\''un numéro d\''appartement de boite au lettres, étage, couloir, escalier pour un particulier. Pour une adresse pro il s\''agit de l\''identité du destinataire et ou service concerné'
      complementAdresse2:
        type: string
        description: '[AFNOR LIGNE 3] - Pour adresse pro/particulière. Contient l\''entrée, le batiment, l\''immeuble, la résidence ou la zone industrielle'
      numeroVoie:
        type: string
        description: '[AFNOR LIGNE 4] - Numéro de voie (caractères numériques)'
      extensionVoieCourt:
        type: string
        description: '[AFNOR LIGNE 4] - Extension du numéro de voie abrégée à une lettre'
        enum:
          - A
          - B
          - C
          - D
          - Q
          - T
      extensionVoieLong:
        type: string
        description: '[AFNOR LIGNE 4] - Extension du numéro de voie version longue'
        enum:
          - A
          - B
          - C
          - D
          - BIS
          - TER
          - QUATER
          - QUINQUIES
      libelleVoie:
        type: string
        description: '[AFNOR LIGNE 4] - Libellé de la voie'
      lieuDit:
        type: string
        description: '[AFNOR LIGNE 5] - Lieu dit ou service particulier de distribution, ou commune géographique pour exceptions'
      codePostal:
        type: string
        description: '[AFNOR LIGNE 6] - Code postal'
      ville:
        type: string
        description: '[AFNOR LIGNE 6] - Ville ou localité de destination'
      codeCedex:
        type: string
        description: '[AFNOR LIGNE 6] - Code CEDEX'
      libelleCedex:
        type: string
        description: '[AFNOR LIGNE 6] - Libelle du CEDEX, généralement correspondant à une localité'
      codeInsee:
        type: string
        description: Code insee de la commune
      dateDebutValidite:
        type: string
        format: date-time
        description: Date de début de validité de l\'adresse
      dateFinValidite:
        type: string
        format: date-time
        description: Date de fin de validité de l\'adresse
      dateInsertion:
        type: string
        format: date-time
        description: Date de création de l\'adresse
      dateModification:
        type: string
        format: date-time
        description: Date de modification de l\'adresse
      deleted:
        type: boolean
        description: Determine wether this entity has been logically deleted
    example:
      extensionVoieLong: A
      dateInsertion: '2000-01-23T04:56:07.000+00:00'
      ville: ville
      dateDebutValidite: '2000-01-23T04:56:07.000+00:00'
      libelleCedex: libelleCedex
      idFonctionnel: idFonctionnel
      dateModification: '2000-01-23T04:56:07.000+00:00'
      numeroVoie: numeroVoie
      codeCedex: codeCedex
      codePostal: codePostal
      nom: nom
      complementAdresse1: complementAdresse1
      complementAdresse2: complementAdresse2
      lieuDit: lieuDit
      libelleVoie: libelleVoie
      deleted: true
      raisonSociale: raisonSociale
      adressePro: true
      extensionVoieCourt: A
      id: 0
      codeInsee: codeInsee
      dateFinValidite: '2000-01-23T04:56:07.000+00:00'
      prenom: prenom
      civilite: civilite
responses: {}
parameters: {}
securityDefinitions: {}
tags:
  - name: organisation
    description: Gestion des organisations
  - name: relation
    description: Gestion des relation d'organisations
  - name: media
    description: Gestion des coordonnées médiatiques d'organisations
  - name: adresse
    description: Gestion des adresses d'organisations
```

### Configuration (browser query string, constructor, config.yaml)

Trying to access swagger ui by doing the following : 

```js
let SwaggerUI = require('swagger-ui');

const ui = SwaggerUI({
    // url: "http://petstore.swagger.io/v2/swagger.json",
    spec: swaggerSpec,
    dom_id: '#swagger-ui',
    presets: [
        SwaggerUI.presets.apis,
        SwaggerUI.SwaggerUIStandalonePreset
    ],
    layout: "StandaloneLayout"
});

app.use(express.static(ui));
app.listen(5000);
```

### Expected Behavior
swagger-ui displaying and consuming services I described in the yaml API spec

### Current Behavior
Server ends up not running with following exception
```
ReferenceError: document is not defined
    at v (C:\_dev\nsi\referentiels\gest_organisations\node_modules\swagger-ui\dist\swagger-ui.js:1:154249)
    at e.exports (C:\_dev\nsi\referentiels\gest_organisations\node_modules\swagger-ui\dist\swagger-ui.js:1:154555)
    at Object.<anonymous> (C:\_dev\nsi\referentiels\gest_organisations\app.js:93:12)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
```

### Possible Solution
[none]

### Context
Actually, I am trying to document already developed endpoints through swagger-ui.
So I use this project to build the inMemory swagger.json : https://github.com/Surnet/swagger-jsdoc<br/>
* swagger.json is built from several configuration and files
* also built from @swagger annotation in JavaScript comments just before methods
* yaml pasted in the issue is the result of this inMemory build, converted to YAML with Swagger-ui editor.

My goal is to end up with Swagger-ui documented apis, within my already coded project.

Best regards,
Denis.

**Comment by dlarr** [comment]
I forgot to mention that same errors goes using SwaggerUiBundle, using my inMemory spec or the URL of the petstore spec (commented out here)

```js
let SwaggerUIBundle = require('swagger-ui-dist').SwaggerUIBundle;
const ui = SwaggerUIBundle({
    // url: "http://petstore.swagger.io/v2/swagger.json",
    spec: swaggerSpec,
    dom_id: '#swagger-ui',
    presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIBundle.SwaggerUIStandalonePreset
    ],
    layout: "StandaloneLayout"
});
```

**Comment by shockey** [comment]
Hi @dlarr! It looks like you're trying to call Swagger-UI inside of an Express application, is this correct?

**Comment by shockey** [comment]
So, what's going on here is that you should be serving Swagger-UI's assets from your express server to your user's browsers, and then calling `SwaggerUI` inside of a browser. 

That's why you're seeing `document is not defined`: `document` is an object built into browsers, but absent in Node.js 😄

**Comment by dlarr** [comment]
I got it :) Thanks for your time
