### ISSUE TITLE
swagger feature trying to locate .png files in swagger jar?!

### ISSUE THREAD

**Issue by bluscreen** [swagger-api/swagger-ui#5310]
Hi everyone

i have found some very strange behavior when trying to download .png files from some endpoint, swagger intercepts and tries to locate the file inside the swagger jar.

i have no idea why but it only seems to happen when someone tries to download a .png file via this endpoint. Other filetypes like .jpg or .html work just fine.

there is some other endpoint which works fine with downloading png files (actually .png is not part of the URL in the other one...)

heres the logs and the endpoint def

```
[INFO ] 11:36:52.195 REQ_IN
    Address: http://127.0.0.1:8080/bla/blub/korrespondenzDatei/3503154/EMV_190417_49600ad1-9299-4659-9f44-27271f28823f.png
    HttpMethod: GET
    ExchangeId: cb76431c-c232-4e1e-addb-dd8d2f5a7eb8
    Headers: {referer=http://localhost:4200/, http.base.path=http://127.0.0.1:8080/bla, Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3, accept-language=de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7, cookie=x=TS; JSESSIONID=y, x-forwarded-proto=http, x-forwarded-port=4200, dnt=1, x-forwarded-for=::1, x-forwarded-host=localhost:4200, host=127.0.0.1:8080, upgrade-insecure-requests=1, connection=close, x-broccoli=[object Object], accept-encoding=gzip, deflate, br, user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36}
 
[WARN ] 11:36:52.230 javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.apache.cxf.jaxrs.swagger.Swagger2Feature$SwaggerUIService.getResource(Swagger2Feature.java:624)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:192)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:103)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:267)
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:191)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:301)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doGet(AbstractHTTPServlet.java:225)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:276)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:441)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:169)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.io.FileNotFoundException: JAR entry META-INF/resources/webjars/swagger-ui/3.2.2/korrespondenzDatei/3503154/EMV_190417_49600ad1-9299-4659-9f44-27271f28823f.png not found in D:\dev\apache-tomcat-8.5.30\temp\0-bla\WEB-INF\lib\swagger-ui-3.2.2.jar
	at sun.net.www.protocol.jar.JarURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(Unknown Source)
	at java.net.URL.openStream(Unknown Source)
	at org.apache.cxf.jaxrs.swagger.Swagger2Feature$SwaggerUIService.getResource(Swagger2Feature.java:618)
	... 47 more

Endpoint

    @GET
    @Produces(MediaType.APPLICATION_OCTET_STREAM)
    @Path("/korrespondenzDatei/{korKorrespondenNr}/{kdaDateiname}")
    public Response getKorrespondenzDateiById(@PathParam("korKorrespondenNr") Long korKorrespondenzNr,
                                              @PathParam("kdaDateiname") String kdaDateiname, @Context HttpHeaders headers)
                    throws AuthorizationException, WSException;
```

As soon as i disable swaggerfeature in endpoints.xml everything works normal.

Any help would be appreciated..

Cheers
Daniel

**Comment by bluscreen** [comment]
anyone investigating?? this is still happening... :(

Caused by: java.io.FileNotFoundException: JAR entry META-INF/resources/webjars/swagger-ui/3.23.8/korrespondenzDatei/123/gahaha.png not found in D:\dev\apache-tomcat-8.5.30\temp\0-webinsureWSREST\WEB-INF\lib\swagger-ui-3.23.8.jar

**Comment by webron** [comment]
This does not seem to be related to Swagger UI, as all the details you give are from Java code, and that's definitely not Swagger UI. If you feel this _is_ related, please file a new issue following the issue template and providing the required details for us to assist.

**Comment by bluscreen** [comment]
Hmm. I See you may find this hard to reproduce but its definately related to swagger somehow.

Sorry but whats the point of closing this now? You might as well just have asked me if you have had any questions..

**Comment by webron** [comment]
Well, for starters, you didn't follow the issue template, which doesn't really allow us to help you out. All the initial questions are there, so you might as well just file a new ticket and provide the information requested. 

Nothing in the details you provided suggests anything to do with Swagger UI. You're showing a Java stacktrace, and even there you're using CXF's implementation which is not ours. We'd love to try to help out, but you at least need to help us help you.
