### ISSUE TITLE
Invalid sourcemaps in dist/

### ISSUE THREAD

**Issue by Lucas-C** [swagger-api/swagger-ui#5598]
# Q&A (please complete the following information)
 - OS: Windows
 - Browser: NA
 - Version: latest (`master` branch)
 - Method of installation: NA
 - Swagger-UI version: latest (`master` branch)
 - Swagger/OpenAPI version: NA

### Describe the bug you're encountering
The `.map` files provided in the `dist/` folder seem to be invalid, based on [sourcemap-validator](https://github.com/ben-ng/sourcemap-validator)

### To reproduce...
1. Install the [`sourcemap-validate` command](https://github.com/ben-ng/sourcemap-validator/pull/15):
`npm install -g git+https://github.com/Lucas-C/sourcemap-validator.git`
2. Execute the following command in this repo:
`sourcemap-validate dist/swagger-ui-bundle.js dist/swagger-ui-bundle.js.map`

### Expected behavior
`Validation OK`

### Additional context or thoughts
Using `sourcemap-validate` I tested that the `Validation OK` message appears up to tag `v3.3.0`. Starting from tag `v3.4.0` the error appears.

I found about this error in https://github.com/springfox/springfox/issues/3114, because my Firefox browser could not load the sourcemaps correctly.

Based on the `package-lock.json` in this repo I cannot pinpoint exactly what version of `webpack-sources` it is using, but this error may be due to [a nasty bug broke sourcemaps it generated before version before `1.4.1`](https://github.com/webpack/webpack/issues/8302#issuecomment-516964714)

**Comment by Lucas-C** [comment]
Here is the stacktrace I get by the way :
```$ sourcemap-validate swagger-ui-bundle.js swagger-ui-bundle.js.map
C:\Users\lucas_cimon\AppData\Roaming\npm\node_modules\sourcemap-validator\index.js:155
          throw new Error(errMsg);
          ^

Error: Warning: mismatched names
Expected: root || 'root' || 'root' || "root" || "root"
Got: (fun || (funct || (funct || (funct || (funct
Original Line: (function webpackUniversalModuleDefinition(root, factory) {
Mapping: 1:10→1:0 "root" in webpack:///webpack/universalModuleDefinition
    at C:\Users\lucas_cimon\AppData\Roaming\npm\node_modules\sourcemap-validator\index.js:155:17
    at Array.forEach (<anonymous>)
    at SourceMapConsumer_eachMapping [as eachMapping] (C:\Users\lucas_cimon\AppData\Roaming\npm\node_modules\sourcemap-validator\node_modules\source-map\lib\source-map\source-map-consumer.js:570:10)
    at validate (C:\Users\lucas_cimon\AppData\Roaming\npm\node_modules\sourcemap-validator\index.js:92:12)
    at Object.<anonymous> (C:\Users\lucas_cimon\AppData\Roaming\npm\node_modules\sourcemap-validator\index.js:166:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```
