### ISSUE TITLE
Cypress issues during testing

### ISSUE THREAD

**Issue by httpways** [swagger-api/swagger-ui#6619]
Hello,

please find below my Linux, NODE + NPM versions:

```
$ uname -a
Linux nick-laptop-ubuntu 4.4.0-178-generic #208-Ubuntu SMP Sun Apr 5 23:45:10 UTC 2020 x86_64 x86_64 x86_64 
GNU/Linux
```
```
$ nodejs -v
v14.11.0
```
```
$ npm version                 
{
  npm: '6.14.8',
  ares: '1.16.0',
  brotli: '1.0.9',
  cldr: '37.0',
  icu: '67.1',
  llhttp: '2.1.2',
  modules: '83',
  napi: '6',
  nghttp2: '1.41.0',
  node: '14.11.0',
  openssl: '1.1.1g',
  tz: '2020a',
  unicode: '13.0',
  uv: '1.39.0',
  v8: '8.4.371.19-node.16',
  zlib: '1.2.11'
}
```

First I am cloning swagger and move to the working directory:
```
$ git clone https://github.com/swagger-api/swagger-ui.git && cd swagger-ui && ls
babel.config.js
composer.json
config/
cypress.json
dev-helpers/
dist/
docker/
Dockerfile
docs/
flavors/
LICENSE
package.json
package-lock.json
README.md
release/
renovate.json
SECURITY.md
snapcraft.yaml
src/
swagger-config.yaml
swagger-ui-dist-package/
test/
webpack/
```

Then I install de dependencies:
```
$ npm install
> iltorb@2.4.5 install /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/iltorb
> node ./scripts/install.js || node-gyp rebuild

info looking for cached prebuild @ /home/nick/.npm/_prebuilds/c57c4d-iltorb-v2.4.5-node-v83-linux-x64.tar.gz
http request GET https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-linux-x64.tar.gz
http 404 https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-linux-x64.tar.gz
WARN install No prebuilt binaries found (target=14.11.0 runtime=node arch=x64 libc= platform=linux)
make : on entre dans le répertoire « /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/iltorb/build »
  CC(target) Release/obj.target/iltorb/brotli/c/common/dictionary.o
  CC(target) Release/obj.target/iltorb/brotli/c/common/transform.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/bit_reader.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/decode.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/huffman.o
  CC(target) Release/obj.target/iltorb/brotli/c/dec/state.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/backward_references.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/backward_references_hq.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/bit_cost.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/block_splitter.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/brotli_bit_stream.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/cluster.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/compress_fragment.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/compress_fragment_two_pass.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/dictionary_hash.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/encode.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/encoder_dict.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/entropy_encode.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/histogram.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/literal_cost.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/memory.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/metablock.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/static_dict.o
  CC(target) Release/obj.target/iltorb/brotli/c/enc/utf8_util.o
  CXX(target) Release/obj.target/iltorb/src/common/allocator.o
  CXX(target) Release/obj.target/iltorb/src/common/stream_coder.o
  CXX(target) Release/obj.target/iltorb/src/dec/stream_decode.o
  CXX(target) Release/obj.target/iltorb/src/dec/stream_decode_worker.o
  CXX(target) Release/obj.target/iltorb/src/enc/stream_encode.o
  CXX(target) Release/obj.target/iltorb/src/enc/stream_encode_worker.o
  CXX(target) Release/obj.target/iltorb/src/iltorb.o
  SOLINK_MODULE(target) Release/obj.target/iltorb.node
  COPY Release/iltorb.node
  COPY ../build/bindings/iltorb.node
  TOUCH Release/obj.target/action_after_build.stamp
make : on quitte le répertoire « /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/iltorb/build »

> chromedriver@86.0.0 install /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/chromedriver
> node install.js

ChromeDriver binary exists. Validating...
ChromeDriver is already available at '/tmp/86.0.4240.22/chromedriver/chromedriver'.
Copying to target path /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/chromedriver/lib/chromedriver
Fixing file permissions.
Done. ChromeDriver binary available at /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/chromedriver/lib/chromedriver/chromedriver

> husky@4.3.0 install /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/husky
> node husky install

husky > Setting up git hooks
Husky requires Git >=2.13.0. Got v2.7.4.
husky > Failed to install

> node-sass@4.14.1 install /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/nick/.npm/node-sass/4.14.1/linux-x64-83_binding.node

> core-js@3.6.5 postinstall /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/@commitlint/cli/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@2.6.11 postinstall /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.6.5 postinstall /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"


> ejs@2.7.4 postinstall /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/ejs
> node ./postinstall.js

Thank you for installing EJS: built with the Jake JavaScript build tool (https://jakejs.com/)


> jsonpath@1.0.2 postinstall /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js


> cypress@5.6.0 postinstall /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/cypress
> node index.js --exec install


Cypress 5.6.0 is installed in /home/nick/.cache/Cypress/5.6.0


> husky@4.3.0 postinstall /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate


> node-sass@4.14.1 postinstall /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/node-sass
> node scripts/build.js

Binary found at /mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/node-sass/vendor/linux-x64-83/binding.node
Testing binary
Binary is fine
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/@babel/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/watchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/mocha/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 3587 packages from 1935 contributors and audited 3662 packages in 123.023s

140 packages are looking for funding
  run `npm fund` for details

found 12 vulnerabilities (9 low, 2 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

Finally I try to run the test, but it fails near the cypress step:
```
$ npm run test

> cypress run


  \{^_^}/ hi!

  Loading test/e2e-selenium/db.json
  Done

  Resources
  http://localhost:3204/pet

  Home
  http://localhost:3204

  Type s + enter at any time to create a snapshot of the database
  Watching...

Cypress could not verify that this server is running:

  > http://localhost:3230/

We are verifying this server because it has been configured as your `baseUrl`.

Cypress automatically waits until your server is accessible before running tests.

We will try connecting to it 3 more times...
We will try connecting to it 2 more times...
We will try connecting to it 1 more time...

Cypress failed to verify that your server is running.

Please start this server and then run Cypress again.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swagger-ui@3.36.2 test-e2e-cypress: `cypress run`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swagger-ui@3.36.2 test-e2e-cypress script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nick/.npm/_logs/2020-11-15T16_00_28_216Z-debug.log
ERROR: "test-e2e-cypress" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swagger-ui@3.36.2 e2e-cypress: `run-p -r hot-e2e-cypress-server mock-api test-e2e-cypress`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swagger-ui@3.36.2 e2e-cypress script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nick/.npm/_logs/2020-11-15T16_00_28_323Z-debug.log
ERROR: "e2e-cypress" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! swagger-ui@3.36.2 test: `run-s just-test-in-node test:unit-jest e2e-cypress lint-errors`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the swagger-ui@3.36.2 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/nick/.npm/_logs/2020-11-15T16_00_28_357Z-debug.log
```

You can find below the output log, I hope it will help.
```
$ cat /home/nick/.npm/_logs/2020-11-15T16_00_28_216Z-debug.log                                                                 coingate/swagger-ui (master=)
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   '--swagger-ui:deps_check_dir=.deps_check',
1 verbose cli   'test-e2e-cypress'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.11.0
4 verbose run-script [ 'pretest-e2e-cypress', 'test-e2e-cypress', 'posttest-e2e-cypress' ]
5 info lifecycle swagger-ui@3.36.2~pretest-e2e-cypress: swagger-ui@3.36.2
6 info lifecycle swagger-ui@3.36.2~test-e2e-cypress: swagger-ui@3.36.2
7 verbose lifecycle swagger-ui@3.36.2~test-e2e-cypress: unsafe-perm in lifecycle true
8 verbose lifecycle swagger-ui@3.36.2~test-e2e-cypress: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/mnt/data/nick/PROJECTS/coingate/swagger-ui/node_modules/.bin:/home/nick/.zplug/repos/zplug/zplug/bin:/home/nick/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/nick/.fzf/bin
9 verbose lifecycle swagger-ui@3.36.2~test-e2e-cypress: CWD: /mnt/data/nick/PROJECTS/coingate/swagger-ui
10 silly lifecycle swagger-ui@3.36.2~test-e2e-cypress: Args: [ '-c', 'cypress run' ]
11 silly lifecycle swagger-ui@3.36.2~test-e2e-cypress: Returned: code: 1  signal: null
12 info lifecycle swagger-ui@3.36.2~test-e2e-cypress: Failed to exec test-e2e-cypress script
13 verbose stack Error: swagger-ui@3.36.2 test-e2e-cypress: `cypress run`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1047:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid swagger-ui@3.36.2
15 verbose cwd /mnt/data/nick/PROJECTS/coingate/swagger-ui
16 verbose Linux 4.4.0-178-generic
17 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "--swagger-ui:deps_check_dir=.deps_check" "test-e2e-cypress"
18 verbose node v14.11.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error swagger-ui@3.36.2 test-e2e-cypress: `cypress run`
22 error Exit status 1
23 error Failed at the swagger-ui@3.36.2 test-e2e-cypress script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

My plan is to customize, re-build, test and ship swagger-ui inside CI/CD pipeline for a project.
So i need the tests to be successful and I don't understand what is going wrong here.

Can you please help solve that issue ?

Thanks a lot for your time and help

Nick

**Comment by tim-lai** [comment]
Hi Nick, checking in if this is still an issue. It appears Cypress is unable to open a server port (localhost:3230). Have you tried running Cypress in dev-mode, `npm run dev-e2e-cypress-open`?

**Comment by tim-lai** [comment]
Closing due to inactivity. One additional comment, one can try re-running the cypress script again, as sometimes it takes 1-3 cypress installs before the runner is able to run successfully.
