### ISSUE TITLE
Swagger UI React is using Legacy API

### ISSUE THREAD

**Issue by anandbmuley** [swagger-api/swagger-ui#7408]
Hi Team,
ReactJS is showing below warning in browser console :

```
index.js:1 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Connect(a), Provider

Learn more about this warning here: https://reactjs.org/link/legacy-context
    at Provider (http://localhost:3000/static/js/vendors~main.chunk.js:106342:5)
    at a (http://localhost:3000/static/js/vendors~main.chunk.js:155761:23)
    at SwaggerUI (http://localhost:3000/static/js/vendors~main.chunk.js:149629:89)
    at div
    at SwaggerVisualizer (http://localhost:3000/static/js/main.chunk.js:3480:5)
    at div
    at div
    at div
    at div
    at Router (http://localhost:3000/static/js/vendors~main.chunk.js:108174:30)
    at BrowserRouter (http://localhost:3000/static/js/vendors~main.chunk.js:107794:35)
    at App (http://localhost:3000/static/js/main.chunk.js:158:5)
```

**Comment by char0n** [comment]
Hi @anandbmuley,

There is an effort being done on v4 release branch that should fix this in foreseeable future: https://github.com/swagger-api/swagger-ui/issues/7341

**Comment by anandbmuley** [comment]
Thank You @char0n  :)

**Comment by anandbmuley** [comment]
Thank You 🙂for your response
