### ISSUE TITLE
Could not render Mt, see the console error upgrading to swagger-ui-react 4.1

### ISSUE THREAD

**Issue by jaydreyer** [swagger-api/swagger-ui#7643]
### Q&A (please complete the following information)
 - OS: [e.g. macOS]
 - Browser: Chrome
 - Version: [e.g. 22]
 - Method of installation: npm
 - Swagger-UI version: 4.1
 - Swagger/OpenAPI version: All

### Content & configuration
It's a local project

### Screenshots
![Screen Shot 2021-11-13 at 8 45 34 PM](https://user-images.githubusercontent.com/1815281/141665474-e1211bcf-517c-4ae3-9a38-9b8bd2b51e7b.png)

### How can we help?
We've been using the v3 versions of `swagger-ui-react` for a couple years with no issues. I'm trying to upgrade to v4.1 but, regardless of the spec that's sent to the component, a `Could not render Mt, see the console.` error appears for every `Example Value`. Clicking `Schema` right next to it works correctly, but clicking back on `Example Value` returns that error. I've cleared the cache a couple of times, stop/restart the server/ui, but the problem persists.

Let me know if there is additional info that could help.

From the console, the following is displayed:
```
index.js:1 TypeError: Cannot read properties of null (reading 'childNodes')
    at swagger-ui.js:2
    at invokePassiveEffectCreate (react-dom.development.js:23487)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at flushPassiveEffectsImpl (react-dom.development.js:23574)
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushPassiveEffects (react-dom.development.js:23447)
    at performSyncWorkOnRoot (react-dom.development.js:22269)
    at react-dom.development.js:11327
    at unstable_runWithPriority (scheduler.development.js:468)
    at runWithPriority$1 (react-dom.development.js:11276)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322)
    at flushSyncCallbackQueue (react-dom.development.js:11309)
    at batchedUpdates$1 (react-dom.development.js:22387)
    at Object.notify (Subscription.js:15)
    at Object.notifyNestedSubs (Subscription.js:85)
    at handleChangeWrapper (Subscription.js:90)
    at dispatch (redux.js:297)
    at swagger-ui.js:2
    at Object.updateResolvedSubtree (redux.js:546)
    at swagger-ui.js:2
    at tryCatch (runtime.js:63)
    at Generator.invoke [as _invoke] (runtime.js:293)
    at Generator.next (runtime.js:118)
    at a (swagger-ui.js:2)
    at s (swagger-ui.js:2) {componentStack: '\n    at Mt (http://localhost:3001/static/js/vendor…t:3001/static/js/vendors~main.chunk.js:185101:23)'} '\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:510930:19)\n    at r (http://localhost:3001/static/js/vendors~main.chunk.js:510979:21)\n    at div\n    at div\n    at div\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:531493:12)\n    at td\n    at tr\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:529242:19)\n    at tbody\n    at table\n    at div\n    at div\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:529104:12)\n    at div\n    at div\n    at qn (http://localhost:3001/static/js/vendors~main.chunk.js:530683:17)\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:530693:19)\n    at div\n    at r (http://localhost:3001/static/js/vendors~main.chunk.js:528650:19)\n    at span\n    at o (http://localhost:3001/static/js/vendors~main.chunk.js:513939:14)\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:526990:12)\n    at a (http://localhost:3001/static/js/vendors~main.chunk.js:510849:23)\n    at ConnectFunction (http://localhost:3001/static/js/vendors~main.chunk.js:502155:75)\n    at div\n    at div\n    at qn (http://localhost:3001/static/js/vendors~main.chunk.js:530683:17)\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:530693:19)\n    at div\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:528559:19)\n    at span\n    at o (http://localhost:3001/static/js/vendors~main.chunk.js:513994:14)\n    at div\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:528461:12)\n    at a (http://localhost:3001/static/js/vendors~main.chunk.js:510849:23)\n    at ConnectFunction (http://localhost:3001/static/js/vendors~main.chunk.js:502155:75)\n    at section\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:530513:19)\n    at div\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:530557:19)\n    at div\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:532177:19)\n    at div\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:532278:19)\n    at a (http://localhost:3001/static/js/vendors~main.chunk.js:510849:23)\n    at ConnectFunction (http://localhost:3001/static/js/vendors~main.chunk.js:502155:75)\n    at n (http://localhost:3001/static/js/vendors~main.chunk.js:527177:19)\n    at a (http://localhost:3001/static/js/vendors~main.chunk.js:510849:23)\n    at ConnectFunction (http://localhost:3001/static/js/vendors~main.chunk.js:502155:75)\n    at Provider (http://localhost:3001/static/js/vendors~main.chunk.js:501866:20)\n    at a (http://localhost:3001/static/js/vendors~main.chunk.js:510875:23)\n    at SwaggerUI (http://localhost:3001/static/js/vendors~main.chunk.js:491058:89)\n    at div\n    at CardContent (http://localhost:3001/static/js/vendors~main.chunk.js:5113:23)\n    at WithStyles (http://localhost:3001/static/js/vendors~main.chunk.js:179084:31)\n    at div\n    at Paper (http://localhost:3001/static/js/vendors~main.chunk.js:19750:23)\n    at WithStyles (http://localhost:3001/static/js/vendors~main.chunk.js:179084:31)\n    at Card (http://localhost:3001/static/js/vendors~main.chunk.js:4797:23)\n    at WithStyles (http://localhost:3001/static/js/vendors~main.chunk.js:179084:31)\n    at div\n    at SectionCard (http://localhost:3001/static/js/main.chunk.js:22166:23)\n    at div\n    at div\n    at CardContent (http://localhost:3001/static/js/vendors~main.chunk.js:5113:23)\n    at WithStyles (http://localhost:3001/static/js/vendors~main.chunk.js:179084:31)\n    at div\n    at Paper (http://localhost:3001/static/js/vendors~main.chunk.js:19750:23)\n    at WithStyles (http://localhost:3001/static/js/vendors~main.chunk.js:179084:31)\n    at Card (http://localhost:3001/static/js/vendors~main.chunk.js:4797:23)\n    at WithStyles (http://localhost:3001/static/js/vendors~main.chunk.js:179084:31)\n    at div\n    at div\n    at PageCard (http://localhost:3001/static/js/main.chunk.js:19926:206)\n    at WithStyles (http://localhost:3001/static/js/vendors~main.chunk.js:179084:31)\n    at div\n    at SwaggerDocUi (http://localhost:3001/static/js/main.chunk.js:22274:206)\n    at WithStyles (http://localhost:3001/static/js/vendors~main.chunk.js:179084:31)\n    at ConnectFunction (http://localhost:3001/static/js/vendors~main.chunk.js:440524:75)\n    at C (http://localhost:3001/static/js/vendors~main.chunk.js:443647:37)\n    at div\n    at DocDetail (http://localhost:3001/static/js/main.chunk.js:38887:206)\n    at WithStyles (http://localhost:3001/static/js/vendors~main.chunk.js:179084:31)\n    at ConnectFunction (http://localhost:3001/static/js/vendors~main.chunk.js:440524:75)\n    at C (http://localhost:3001/static/js/vendors~main.chunk.js:443647:37)\n    at Route (http://localhost:3001/static/js/vendors~main.chunk.js:443390:29)\n    at Switch (http://localhost:3001/static/js/vendors~main.chunk.js:443592:29)\n    at div\n    at div\n    at Docs (http://localhost:3001/static/js/main.chunk.js:39227:206)\n    at WithStyles (http://localhost:3001/static/js/vendors~main.chunk.js:179084:31)\n    at ConnectFunction (http://localhost:3001/static/js/vendors~main.chunk.js:440524:75)\n    at C (http://localhost:3001/static/js/vendors~main.chunk.js:443647:37)\n    at Route (http://localhost:3001/static/js/vendors~main.chunk.js:443390:29)\n    at PrivateRoute (http://localhost:3001/static/js/main.chunk.js:20109:24)\n    at C (http://localhost:3001/static/js/vendors~main.chunk.js:443647:37)\n    at Switch (http://localhost:3001/static/js/vendors~main.chunk.js:443592:29)\n    at div\n    at div\n    at div\n    at Layout (http://localhost:3001/static/js/main.chunk.js:43749:206)\n    at WithStyles (http://localhost:3001/static/js/vendors~main.chunk.js:179084:31)\n    at ConnectFunction (http://localhost:3001/static/js/vendors~main.chunk.js:440524:75)\n    at C (http://localhost:3001/static/js/vendors~main.chunk.js:443647:37)\n    at Route (http://localhost:3001/static/js/vendors~main.chunk.js:443390:29)\n    at Switch (http://localhost:3001/static/js/vendors~main.chunk.js:443592:29)\n    at Router (http://localhost:3001/static/js/vendors~main.chunk.js:443021:30)\n    at BrowserRouter (http://localhost:3001/static/js/vendors~main.chunk.js:442642:35)\n    at ThemeProvider (http://localhost:3001/static/js/vendors~main.chunk.js:177786:24)\n    at App (http://localhost:3001/static/js/main.chunk.js:36616:85)\n    at Provider (http://localhost:3001/static/js/vendors~main.chunk.js:440237:20)\n    at RenderChildren (http://localhost:3001/static/js/vendors~main.chunk.js:184793:24)\n    at http://localhost:3001/static/js/vendors~main.chunk.js:184843:34\n    at AuthenticationProvider (http://localhost:3001/static/js/vendors~main.chunk.js:185101:23)'
console.<computed> @ index.js:1
overrideMethod @ react_devtools_backend.js:2540
value @ swagger-ui.js:2
callback @ react-dom.development.js:20159
callCallback @ react-dom.development.js:12318
commitUpdateQueue @ react-dom.development.js:12339
commitLifeCycles @ react-dom.development.js:20709
commitLayoutEffects @ react-dom.development.js:23426
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
commitRootImpl @ react-dom.development.js:23151
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
commitRoot @ react-dom.development.js:22990
performSyncWorkOnRoot @ react-dom.development.js:22329
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
batchedUpdates$1 @ react-dom.development.js:22387
notify @ Subscription.js:15
notifyNestedSubs @ Subscription.js:85
handleChangeWrapper @ Subscription.js:90
dispatch @ redux.js:297
(anonymous) @ swagger-ui.js:2
(anonymous) @ redux.js:546
(anonymous) @ swagger-ui.js:2
tryCatch @ runtime.js:63
invoke @ runtime.js:293
(anonymous) @ runtime.js:118
a @ swagger-ui.js:2
s @ swagger-ui.js:2
Promise.then (async)
a @ swagger-ui.js:2
s @ swagger-ui.js:2
(anonymous) @ swagger-ui.js:2
t @ swagger-ui.js:2
(anonymous) @ swagger-ui.js:2
y @ swagger-ui.js:2
S @ swagger-ui.js:2
x @ swagger-ui.js:2
setTimeout (async)
b @ swagger-ui.js:2
w @ swagger-ui.js:2
(anonymous) @ swagger-ui.js:2
(anonymous) @ swagger-ui.js:2
(anonymous) @ redux.js:546
(anonymous) @ swagger-ui.js:2
(anonymous) @ swagger-ui.js:2
callCallback @ react-dom.development.js:3945
invokeGuardedCallbackDev @ react-dom.development.js:3994
invokeGuardedCallback @ react-dom.development.js:4056
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4070
executeDispatch @ react-dom.development.js:8243
processDispatchQueueItemsInOrder @ react-dom.development.js:8275
processDispatchQueue @ react-dom.development.js:8288
dispatchEventsForPlugins @ react-dom.development.js:8299
(anonymous) @ react-dom.development.js:8508
batchedEventUpdates$1 @ react-dom.development.js:22396
batchedEventUpdates @ react-dom.development.js:3745
dispatchEventForPluginEventSystem @ react-dom.development.js:8507
attemptToDispatchEvent @ react-dom.development.js:6005
dispatchEvent @ react-dom.development.js:5924
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
discreteUpdates$1 @ react-dom.development.js:22413
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
Show 4 more frames
```

**Comment by jaydreyer** [comment]
This somehow ended up working after a while. No idea why. All good now so closing.
