### ISSUE TITLE
Flaky Cypress test 5043

### ISSUE THREAD

**Issue by tim-lai** [swagger-api/swagger-ui#7768]
### Q&A (please complete the following information)
 - OS: CI - Ubuntu
 - Browser: CI
 - Version: [e.g. 22]
 - Method of installation: CI
 - Swagger-UI version: 4.1.3
 - Swagger/OpenAPI version: n/a

### Content & configuration

Use existing Cypress test configuration

### Describe the bug you're encountering

CI Cypress run, test `bugs/5043.js` intermittent fails. One instance has blocked a version release, other instances include dependency updates.

### To reproduce...

1. `Run npx start-server-and-test cy:start http://localhost:3204 'npm run cy:run -- --spec "test/e2e-cypress/tests/+(a11y|security|bugs)/**/*.js"'`

### Screenshots

```
Running:  bugs/5043.js                                                                   (8 of 35)
[2052:0118/212535.367639:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")


  #5043: path-level $ref path items should inherit global consumes/produces
    1) should render consumes options correctly
    2) should render produces options correctly


  0 passing (4s)
  2 failing

  1) #5043: path-level $ref path items should inherit global consumes/produces
       should render consumes options correctly:
     TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cannot read properties of undefined (reading 'resultMap')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
      at _callee3$ (http://localhost:3230/swagger-ui-bundle.js:207551:61)
      at tryCatch (http://localhost:3230/swagger-ui-bundle.js:164223:40)
      at Generator.invoke [as _invoke] (http://localhost:3230/swagger-ui-bundle.js:164454:22)
      at Generator.throw (http://localhost:3230/swagger-ui-bundle.js:164279:21)
      at asyncGeneratorStep (http://localhost:3230/swagger-ui-bundle.js:1586:24)
      at _throw (http://localhost:3230/swagger-ui-bundle.js:1612:9)

  2) #5043: path-level $ref path items should inherit global consumes/produces
       should render produces options correctly:
     TypeError: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Cannot read properties of undefined (reading 'resultMap')

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
      at _callee3$ (http://localhost:3230/swagger-ui-bundle.js:207551:61)
      at tryCatch (http://localhost:3230/swagger-ui-bundle.js:164223:40)
      at Generator.invoke [as _invoke] (http://localhost:3230/swagger-ui-bundle.js:164454:22)
      at Generator.throw (http://localhost:3230/swagger-ui-bundle.js:164279:21)
      at asyncGeneratorStep (http://localhost:3230/swagger-ui-bundle.js:1586:24)
      at _throw (http://localhost:3230/swagger-ui-bundle.js:1612:9)


```

### Additional context or thoughts

Not sure if this is related, but the CI logs also yield the following:
```
Opening Cypress...
WARNING: 3 repetitive deprecation warnings omitted.

[2052:0118/212430.599913:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2052:0118/212430.600018:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2229:0118/212430.640568:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is 
```

**Comment by tim-lai** [comment]
example ci run: https://github.com/swagger-api/swagger-ui/runs/4859561540?check_suite_focus=true
