### ISSUE TITLE
swagger-ui-react - Object(...) is not a function when executing a query via 'Try-it-now'

### ISSUE THREAD

**Issue by philipwhiuk** [swagger-api/swagger-ui#7844]
### Q&A
 - OS: MacOS
 - Browser: Chrome
 - Version: 98
 - Method of installation: NPM
 - Swagger-UI version: 4.5.0
 - Swagger/OpenAPI version: Swagger 2.0

### Content & configuration

Using Swagger embedded via React component:
`<SwaggerUI url="/swagger.json" />`

REST API path
```
    "/part/{id}/action" : {
      "post" : {
        "tags" : [ "REST API" ],
        "summary" : "Action",
        "description" : "",
        "operationId" : "action",
        "parameters" : [ {
          "name" : "id",
          "in" : "path",
          "description" : "ID of the item",
          "required" : true,
          "type" : "string"
        }, {
          "in" : "body",
          "name" : "body",
          "description" : "The action information",
          "required" : false,
          "schema" : {
            "$ref" : "#/definitions/ActionData"
          },
          "x-examples" : {
            "application/json" : "{\"reason\": \"Reason\", \"duration\": 1 }"
          }
        }, {
          "name" : "apiToken",
          "in" : "query",
          "description" : "The API Token to authenticate this request with",
          "required" : true,
          "type" : "string"
        } ],
        "responses" : {
          "200" : {
            "description" : "Indicates successful action"
          },
          "415" : {
            "description" : "Returned when a non-JSON request is sent"
          },
          "401" : {
            "description" : "Returned when an API token is not provided or not permitted to perform this request"
          }
        }
      }
    },
```
Schema object
```
    "Action" : {
      "type" : "object",
      "required" : [ "duration", "reason" ],
      "properties" : {
        "reason" : {
          "type" : "string"
        },
        "duration" : {
          "type" : "integer",
          "format" : "int32"
        }
      }
    },
```

### Describe the bug you're encountering

When filling in the API token and id in the 'Try-it-out' button:
```
react_devtools_backend.js:4061 TypeError: Object(...) is not a function
    at Object.nn [as execute] (swagger-ui.js:2:1)
    at swagger-ui.js:2:1
    at Object.dispatch (swagger-ui.js:2:1)
    at dispatch (<anonymous>:3665:80)
    at redux.js:554:1
    at swagger-ui.js:2:1
    at Object.r (swagger-ui.js:2:1)
    at Object.executeRequest (swagger-ui.js:2:1)
    at swagger-ui.js:2:1
    at Object.dispatch (swagger-ui.js:2:1)
```

### To reproduce...

1. Go to the Action
2. Click "Try it out"
2. Fill in the ID & apiToken
3. Click execute
4. Action will hang and JS Console will show error similar to above

### Expected behavior

Either a debuggable error or successful submission

NB, if there's a way to use non-minified version so I can debug this myself let me know.

**Comment by PavelPolyakov** [comment]
This is the same as https://github.com/swagger-api/swagger-ui/issues/7797

**Comment by philipwhiuk** [comment]
Thanks - mentioned workaround seems to work. Closing
