### ISSUE TITLE
Missing start boundary for multipart body

### ISSUE THREAD

**Issue by naraesk** [swagger-api/swagger-ui#8181]
### Q&A (please complete the following information)
 - OS: Linux
 - Browser: Chrome / Firefox
 - Version: 105/104
 - Method of installation: npm
 - Swagger-UI version: using swagger-jaxrs2-jakarta/2.2.2
 - OpenAPI version: OpenAPI 3.0

### Content & configuration
Example Swagger/OpenAPI definition:
```yaml
openapi: 3.0.3
info:
  title: FormData MultiPart Example
  version: 1.0.0
paths:
  /foo:
    post:
      operationId: updatePet
      parameters:
        - name: id
          in: query
          required: true
          schema:
            pattern: ^(?!aliases$)(?!ids$)[-_.a-zA-Z0-9]+$
            type: string
        - name: additionalMetadata
          in: query
          description: Additional Metadata
          required: false
          schema:
            type: string
      requestBody:
        content: 
          multipart/form-data: # Media type
            schema:   
              type: string
              format: binary
      responses:
        '200':
          description: Successful operation
```

### Describe the bug you're encountering
It seems that there is no start boundary set. Chrome Dev Tools also only show the end boundary but no start boundary. This leads to the following exception on the server:
``` java
Caused by: org.jvnet.mimepull.MIMEParsingException: Missing start boundary
at org.jvnet.mimepull.MIMEParser.skipPreamble(MIMEParser.java:288)
at org.jvnet.mimepull.MIMEParser.access$300(MIMEParser.java:38)
at org.jvnet.mimepull.MIMEParser$MIMEEventIterator.next(MIMEParser.java:124)
at org.jvnet.mimepull.MIMEParser$MIMEEventIterator.next(MIMEParser.java:102)
at org.jvnet.mimepull.MIMEMessage.makeProgress(MIMEMessage.java:199)
at org.jvnet.mimepull.MIMEMessage.parseAll(MIMEMessage.java:160)
at org.jvnet.mimepull.MIMEMessage.getAttachments(MIMEMessage.java:86)
```

### To reproduce...

Just fill out the form and have a look at the request header

### Expected behavior
There should be a start boundary set, but there isn't any.

### Screenshots
![image](https://user-images.githubusercontent.com/7393797/190470864-869f9b23-04f5-4f08-96d4-a91d9712ab49.png)

### Additional context or thoughts
The curl command produced by swagger-ui works as expected, there the start boundary is set.

**Comment by LouCastaldo** [comment]
Having same issue, has this been resolved ?

**Comment by hkosova** [comment]
@naraesk change the `requestBody` as follows:

```yaml
      requestBody:
        content: 
          multipart/form-data:
            schema:
              type: object
              properties:
                myFile:  # The name of the form field that contains the file
                  type: string
                  format: binary
```
As explained in [Multipart Requests](https://swagger.io/docs/specification/describing-request-body/multipart-requests/), the request body `schema` must be `type: object` whose properties represent individual parts (form fields) of a multipart request.

**Comment by LouCastaldo** [comment]
My request looks like below.  I get a 200 back but it only passes the pdf file as an attachement but does not pass the Json part at all.  Any ideas ?  The "encoding" keyword does not seem to do anything at all.

      requestBody:
        content:
          multipart/form-data:
              schema:
                description: The main schema representing the multipart body.
                type: object
                properties:
                  json:
                    $ref: '#/components/schemas/request-wrapper'
                  files:
                    type: array
                    items:
                      type: string
                      format: binary
              encoding:
                json: 
                  contentType: application/json
                files:
                  contentType: application/pdf

components:
  schemas:
    request-wrapper:
      type: object
      properties:
        SomeID:
          type: string
