### ISSUE TITLE
Remix: SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by louislefebvre** [swagger-api/swagger-ui#8321]
### Q&A
 - OS: Ubuntu 22.10
 - Browser: firefox
 - Version: 109.0b2
 - Method of installation: `pnpm add swagger-react-ui` 
 - Swagger-UI version: [e.g. 3.10.0]
 - Swagger/OpenAPI version: [e.g. Swagger 2.0, OpenAPI 3.0]

### Content & configuration

I am using React Remix framework: https://remix.run

```tsx
import SwaggerUI from "swagger-ui-react";

const Example = () => {
  return <SwaggerUI url="https://petstore.swagger.io/v2/swagger.json" />;
};

export default Example;
```

The upper code throws this error:
```
/home/louis/Dev/remix/node_modules/.pnpm/swagger-ui-react@4.15.5_biqbaboplfbrettd7655fr4n2y/node_modules/swagger-ui-react/swagger-ui-es-bundle-core.js:2
import*as e from"react-immutable-pure-component";import*as t from"remarkable/linkify";import*as r from"dompurify";import*as a from"zenscroll";import*as n from"lodash/reduce";import*as l from"@babel/runtime-corejs3/core-js-stable/instance/repeat";import*as s from"@babel/runtime-corejs3/core-js-stable/instance/fill";
[...]
(h.specActions.updateUrl(r.url),h.specActions.download(r.url))),r.domNode)h.render(r.domNode,"App");else if(r.dom_id){let e=document.querySelector(r.dom_id);h.render(e,"App")}else null===r.dom_id||null===r.domNode||console.error("Skipped rendering: no `dom_id` or `domNode` was specified");return h},g=i.config||c.configUrl;return g&&h.specActions&&h.specActions.getConfigByUrl?(h.specActions.getConfigByUrl({url:g,loadRemoteConfig:!0,requestInterceptor:c.requestInterceptor,responseInterceptor:c.responseInterceptor},m),h):m()}Wr.presets={apis:Ur},Wr.plugins=Vr.default;const Hr=Wr})();var Ye=Ze.Z;export{Ye as default};
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/louis/Dev/remix/node_modules/.pnpm/swagger-ui-react@4.15.5_biqbaboplfbrettd7655fr4n2y/node_modules/swagger-ui-react/commonjs.js:7:53)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
```

### To reproduce

1. `npx create-remix@latest` then follow the cli instructions
2. `npm i --save swagger-ui-react`
3. `npm i --save-dev @types/swagger-ui-react`
4. In `app/routes/index.tsx`, remove the content and replace it with:
```tsx
import SwaggerUI from "swagger-ui-react";
import "swagger-ui-react/swagger-ui.css";

export default function App() {
  return <SwaggerUI />;
}
```
5. Go to `localhost:3000` in your browser, and the error should be there.

### Additional context or thoughts
I have seen other issues such as https://github.com/swagger-api/swagger-ui/issues/8245 and https://github.com/swagger-api/swagger-ui/issues/7970, however the fix is only for NextJS framework.

In Remix discord server, people had the same issue with `SyntaxError: Cannot use import statement outside a module`, and it was advised to use `serverDependenciesToBundle` (https://remix.run/docs/en/v1/file-conventions/remix-config#serverdependenciestobundle), however it did not fix the issue on my side:

remix.config.js
```js
/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ["**/.*"],
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // serverBuildPath: "build/index.js",
  // publicPath: "/build/",
serverDependenciesToBundle: ["swagger-ui-react"],
};
```

Note: The SyntaxError is still there, but the underlined import is different.

```
/home/louis/Dev/my-remix-app/node_modules/swagger-client/es/resolver.js:1
import _asyncToGenerator from "@babel/runtime-corejs3/helpers/asyncToGenerator";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1088:15)
    at Module._compile (node:internal/modules/cjs/loader:1123:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/louis/Dev/my-remix-app/build/index.js:195:758)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
```

**Comment by EmlynC** [comment]
For this particular use case of adding Swagger UI docs to a Remix.run application, I added a static HTML file to the `public/` directory and then redirected from one of my routes to this:

```
<html>
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.19.5/swagger-ui.css">
  <style>
      .topbar {
          display: none;
      }
  </style>
</head>

<body>
<div id="swagger-ui"></div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.19.5/swagger-ui-bundle.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/3.19.5/swagger-ui-standalone-preset.js"></script>
<script>
  window.onload = function() {
    const ui = SwaggerUIBundle({
      url: '/openapi.yaml',
      dom_id: "#swagger-ui",
      deepLinking: true,
      presets: [
        SwaggerUIBundle.presets.apis,
        SwaggerUIStandalonePreset
      ],
      plugins: [
        SwaggerUIBundle.plugins.DownloadUrl
      ],
      layout: "StandaloneLayout"
    });

    window.ui = ui;
  };
</script>
</body>
</html>
```

Similarly, I couldn't figure out how to use `serverDependenciesToBundle` or esbuild overrides (`remix-esbuild-override`)

**Comment by erwan-joly** [comment]
this seems to works:

create swagger.client.ts:

import SwaggerUI from "swagger-ui-react";

export const Swagger: React.FC = () => {
    return <SwaggerUI url={`the address to json`}></SwaggerUI>;
};

in the place you want the code

import { ClientOnly } from 'remix-utils';
<ClientOnly>
   {() => <Swagger />}
</ClientOnly>

**Comment by soyuka** [comment]
should be closed
