### ISSUE TITLE
Parcel Build for Swagger-UI not working for v4.9 and greater.

### ISSUE THREAD

**Issue by ABWalters** [swagger-api/swagger-ui#8340]
### Q&A
 - OS: macOS 13.1
 - Browser: Chrome, Firefox
 - Method of installation: npm
 - Swagger-UI version: 4.15.5

### Content & configuration
The build setup and dependencies that I am using can be viewed in the following repo:
https://github.com/totakura/parcel-swagger-ui

- parcel@2.8.2
- swagger-ui@4.15.5

After running parcel for the first time, it gave the following message:
```
@parcel/resolver-default: Auto installing polyfill for Node builtin module "buffer"...
```

And added the following dependencies to the package.json
- buffer@5.7.1
- punycode@1.3.2

### Describe the bug you're encountering
I am trying to do a simple import and instantiation of the swagger UI library, like so:
```javascript
// app.js
import SwaggerUI from 'swagger-ui';

SwaggerUI({
  dom_id: '#swagger-ui'
});
```

I then get the following error message in the browser console:
```bash
Uncaught TypeError: Class extends value undefined is not a constructor or null
```

If I try to follow the stack trace, it looks like the error originates from [memoizeN.js](https://github.com/swagger-api/swagger-ui/blob/master/src/helpers/memoizeN.js)
```javascript
// memoizeN.js
class Cache extends Map {
  delete(key) {
    const keys = Array.from(this.keys())
    const foundKey = keys.find(shallowArrayEquals(key))
    return super.delete(foundKey)
  }

  get(key) {
    const keys = Array.from(this.keys())
    const foundKey = keys.find(shallowArrayEquals(key))
    return super.get(foundKey)
  }

  has(key) {
    const keys = Array.from(this.keys())
    return keys.findIndex(shallowArrayEquals(key)) !== -1
  }
}
```

It's unclear to me why this would be the case, as Map should be defined in the browser.

### To reproduce...

Steps to reproduce the behaviour:
1. Install the latest version of parcel and swagger-ui
2. Try to import swagger-ui in a javascript file using the default parcel config
3. Open your browser and view the error message in the console.

### Expected behavior
I would expect parcel to be able to build the code correctly.

It seems to correctly identify the need for buffer and Punycode polyfills. I can't understand why the error would originate with `Map` being undefined. Perhaps the browser is not correctly identifying where the exception originates.

**Comment by aamiriqubal** [comment]
I did check and this problem is not with the browser but something specifically wrong with these versions. Even tried with the latest swagger-ui-react, and same issue ☝️.

**Comment by aamiriqubal** [comment]
I did check and this problem is not with the browser but something specifically wrong with these versions. Even tried with the latest swagger-ui-react, and same issue ☝️.
Any luck in 6 months? @ABWalters

**Comment by martin-badin** [comment]
issue still prersist

`⨯ unhandledRejection: TypeError: Class extends value undefined is not a constructor or null
    at /Users/mbadin/Documents/projects/lead-generation-sites/node_modules/swagger-ui-react/swagger-ui-bundle.js:2:809860
    at /Users/mbadin/Documents/projects/lead-generation-sites/node_modules/swagger-ui-react/swagger-ui-bundle.js:2:1398989
    at /Users/mbadin/Documents/projects/lead-generation-sites/node_modules/swagger-ui-react/swagger-ui-bundle.js:2:1399005
    at webpackUniversalModuleDefinition (/Users/mbadin/Documents/projects/lead-generation-sites/node_modules/swagger-ui-react/swagger-ui-bundle.js:2:114)
    at Object.<anonymous> (/Users/mbadin/Documents/projects/lead-generation-sites/node_modules/swagger-ui-react/swagger-ui-bundle.js:2:244)
`
