### ISSUE TITLE
Invalid hook call with swagger-ui 4.18.0 to 4.18.2

### ISSUE THREAD

**Issue by tsyjonlau** [swagger-api/swagger-ui#8581]
### Q&A 
 - OS: Windows 10 Professional x64
 - Browser: Google Chrome 112.0.5615.122 and Firefox 112.0.1
 - Method of installation: yarn
 - Swagger-UI version: 4.18.0 to 4.18.2
 - Swagger/OpenAPI version: OpenApi 3.0.3

### Content & configuration
Here is the list of dependencies in my `package.json`

```json
  "dependencies": {
    "@date-io/dayjs": "2.16.0",
    "@emotion/react": "11.10.6",
    "@emotion/styled": "11.10.6",
    "@fortawesome/fontawesome-free": "6.4.0",
    "@material-ui/core": "4.12.4",
    "@material-ui/styles": "4.11.5",
    "@mui/icons-material": "5.11.16",
    "@mui/lab": "5.0.0-alpha.126",
    "@mui/material": "5.12.0",
    "@mui/x-date-pickers": "5.0.20",
    "a_custom_library": "1.0.11",
    "@reduxjs/toolkit": "1.9.3",
    "@sentry/browser": "7.47.0",
    "@sentry/integrations": "7.47.0",
    "@sentry/react": "7.47.0",
    "@uppy/core": "3.1.2",
    "@uppy/dashboard": "3.3.2",
    "@uppy/drag-drop": "3.0.1",
    "@uppy/file-input": "3.0.1",
    "@uppy/image-editor": "2.1.1",
    "@uppy/locales": "3.1.0",
    "@uppy/progress-bar": "3.0.1",
    "@uppy/react": "3.1.1",
    "@uppy/screen-capture": "3.1.0",
    "@uppy/webcam": "3.3.0",
    "@uppy/xhr-upload": "3.1.1",
    "autosuggest-highlight": "3.3.4",
    "bootstrap-sass": "3.4.3",
    "chart.js": "3.9.1",
    "chartjs-adapter-dayjs-3": "1.2.3",
    "chartjs-plugin-zoom": "2.0.1",
    "classnames": "2.3.2",
    "core-js": "3.30.1",
    "datatables.net": "1.13.4",
    "datatables.net-bs": "1.13.4",
    "datatables.net-colreorder": "1.6.2",
    "datatables.net-colreorder-bs": "1.6.2",
    "datatables.net-colresize-unofficial": "1.7.1",
    "datatables.net-responsive": "2.4.1",
    "datatables.net-responsive-bs": "2.4.1",
    "date-arithmetic": "4.1.0",
    "dayjs": "1.11.7",
    "jquery": "3.6.4",
    "moment": "2.29.4",
    "notistack": "3.0.1",
    "prop-types": "15.8.1",
    "react": "18.2.0",
    "react-autosuggest": "10.1.0",
    "react-big-calendar": "1.6.9",
    "react-chartjs-2": "4.3.1",
    "react-dom": "18.2.0",
    "react-redux": "8.0.5",
    "react-rte": "0.16.5",
    "react-transition-group": "4.4.5",
    "regenerator-runtime": "0.13.11",
    "select2": "4.0.13",
    "select2-bootstrap-theme": "a-fork-of/select2-bootstrap-theme",
    "swagger-ui": "4.18.2",
    "uuid": "9.0.0",
    "wavesurfer.js": "6.6.3",
    "xml-js": "1.6.11"
  }
```

The a_custom_library package.json dependencies are :
```json
  "dependencies": {
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@mui/material": "^5.11.1",
    "@semantic-release/changelog": "^6.0.2",
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "typescript": "^4.9.4"
  },
```

Swagger-UI configuration options:
```js
SwaggerUI({
    url: '/docs/dev/mydoc.yaml',
    dom_id: '#swagger-ui',
  });
```

### Describe the bug you're encountering
From swagger-ui 4.18.0 onwards, our swagger page crashes and it displays the following error messages, regardless of what content is inside the swagger yaml file.

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem. 
    at Provider (http://localhost:6543/static/bundles/docs_dev.min.a7787772d82e1f554b71.js:75913:3)
    at s (http://localhost:6543/static/bundles/docs_dev.min.a7787772d82e1f554b71.js:92785:106502)
```

```
Uncaught TypeError: Cannot read properties of null (reading 'useMemo')
    at useMemo (react.development.js:1650:1)
    at Provider (Provider.js:12:31)
    at renderWithHooks (react-dom.development.js:14985:1)
    at mountIndeterminateComponent (react-dom.development.js:17811:1)
    at beginWork (react-dom.development.js:19049:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at beginWork$1 (react-dom.development.js:23964:1)
    at performUnitOfWork (react-dom.development.js:22776:1)
```

```
The above error occurred in the <Provider> component:

    at Provider (http://localhost:6543/static/bundles/docs_dev.min.a7787772d82e1f554b71.js:75913:3)
    at s (http://localhost:6543/static/bundles/docs_dev.min.a7787772d82e1f554b71.js:92785:106502)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
```

### Expected behavior
There are not any crashes when reverting back to `swagger-ui@4.17.1` so I guess that there is something that changes and didn't interact well with React or some other dependency.

### Screenshots
![image](https://user-images.githubusercontent.com/17789916/233389010-097e8046-4c5c-4261-8d27-c2296a31b8d1.png)

**Comment by rokasandreikenas** [comment]
We are facing the same issue.

**Comment by christ-offer** [comment]
I have been facing the same issue lately, but Im still running 4.15.5

**Comment by char0n** [comment]
Here is the list of changes between 4.17.1 and 4.18.0:

https://github.com/swagger-api/swagger-ui/compare/v4.17.1...v4.18.0


react-redux has been updated from 7.2.9 to 8.0.5. I don't see anything else that could cause your issues.

**Comment by olemoign** [comment]
Sorry, I'm a terrible js dev.

If I look at my lockfile, I see that I used to have two versions of react and two versions of react-redux.
Now that react-redux has been updated, there is only one react-redux, with still 2 react (react 17.0.2 for swagger-ui, react 18.2.0 for the rest of my app). 

Could it be that react-redux now links to the "wrong" react, which leads to the error here? What is my solution?
