### ISSUE TITLE
OpenAPI 3.1.0 console error when running dev environment with oneOf/anyOf

### ISSUE THREAD

**Issue by jux61** [swagger-api/swagger-ui#9410]
### Q&A (please complete the following information)
 - OS: windows10
 - Browser: chrome 119.0.6045.160 / firefox 120.0
 - Version: 5.10.3
 - Method of installation: clone git repo
 - Swagger-UI version: 5.10.3
 - Swagger/OpenAPI version: OpenAPI 3.1

### Content & configuration
Error in browser console
```
react-dom.development.js:67 Warning: React has detected a change in the order of Hooks called by OneOf. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://reactjs.org/link/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useContext                 useContext
2. useContext                 useContext
3. useState                   useState
4. useState                   useState
5. useContext                 useContext
6. useContext                 useContext
7. useContext                 useContext
8. useContext                 useContext
9. useCallback                useCallback
10. useCallback               useCallback
11. undefined                 useContext
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    at OneOf (http://localhost:3200/swagger-ui-bundle.js:29345:18)
    at div
    at article
    at http://localhost:3200/swagger-ui-bundle.js:26643:6
    at http://localhost:3200/swagger-ui-bundle.js:34129:106
    at HOC
    at _c (http://localhost:3200/swagger-ui-bundle.js:36911:4)
    at div
    at ModelWrapper (http://localhost:3200/swagger-ui-bundle.js:10996:1)
    at ErrorBoundary (http://localhost:3200/swagger-ui-bundle.js:41381:5)
    at WithErrorBoundary (http://localhost:3200/swagger-ui-bundle.js:41546:3)
    at div
    at div
    at ModelExample (http://localhost:3200/swagger-ui-bundle.js:10816:5)
    at div
    at RequestBody (http://localhost:3200/swagger-ui-bundle.js:38484:3)
    at WithSystem (http://localhost:3200/swagger-ui-bundle.js:43768:3)
    at ConnectFunction (http://localhost:3200/swagger-ui-bundle.js:116381:103)
    at div
    at div
    at div
    at Parameters (http://localhost:3200/swagger-ui-bundle.js:14186:5)
    at ErrorBoundary (http://localhost:3200/swagger-ui-bundle.js:41381:5)
    at WithErrorBoundary (http://localhost:3200/swagger-ui-bundle.js:41546:3)
    at div
    at div
    at NoMargin (http://localhost:3200/swagger-ui-bundle.js:10065:21)
    at Collapse (http://localhost:3200/swagger-ui-bundle.js:10071:1)
    at div
    at Operation (http://localhost:3200/swagger-ui-bundle.js:12702:1)
    at span
    at OperationWrapper (http://localhost:3200/swagger-ui-bundle.js:19456:34)
    at OperationContainer (http://localhost:3200/swagger-ui-bundle.js:16167:5)
    at ErrorBoundary (http://localhost:3200/swagger-ui-bundle.js:41381:5)
    at WithErrorBoundary (http://localhost:3200/swagger-ui-bundle.js:41546:3)
    at WithSystem (http://localhost:3200/swagger-ui-bundle.js:43768:3)
    at ConnectFunction (http://localhost:3200/swagger-ui-bundle.js:116381:103)
    at div
    at div
    at NoMargin (http://localhost:3200/swagger-ui-bundle.js:10065:21)
    at Collapse (http://localhost:3200/swagger-ui-bundle.js:10071:1)
    at div
    at OperationTag (http://localhost:3200/swagger-ui-bundle.js:12521:1)
    at span
    at OperationTagWrapper (http://localhost:3200/swagger-ui-bundle.js:19379:34)
    at div
    at Operations (http://localhost:3200/swagger-ui-bundle.js:13008:1)
    at WithSystem (http://localhost:3200/swagger-ui-bundle.js:43768:3)
    at ConnectFunction (http://localhost:3200/swagger-ui-bundle.js:116381:103)
    at section
    at Col (http://localhost:3200/swagger-ui-bundle.js:9881:1)
    at div
    at Row (http://localhost:3200/swagger-ui-bundle.js:9944:1)
    at div
    at VersionPragmaFilter (http://localhost:3200/swagger-ui-bundle.js:34408:3)
    at div
    at BaseLayout (http://localhost:3200/swagger-ui-bundle.js:10165:1)
    at ErrorBoundary (http://localhost:3200/swagger-ui-bundle.js:41381:5)
    at WithErrorBoundary (http://localhost:3200/swagger-ui-bundle.js:41546:3)
    at WithSystem (http://localhost:3200/swagger-ui-bundle.js:43768:3)
    at ConnectFunction (http://localhost:3200/swagger-ui-bundle.js:116381:103)
    at section
    at Container (http://localhost:3200/swagger-ui-bundle.js:9853:1)
    at StandaloneLayout (http://localhost:3200/swagger-ui-standalone-preset.js:2745:1)
    at ErrorBoundary (http://localhost:3200/swagger-ui-bundle.js:41381:5)
    at WithErrorBoundary (http://localhost:3200/swagger-ui-bundle.js:41546:3)
    at WithSystem (http://localhost:3200/swagger-ui-bundle.js:43768:3)
    at ConnectFunction (http://localhost:3200/swagger-ui-bundle.js:116381:103)
    at App (http://localhost:3200/swagger-ui-bundle.js:5681:1)
    at ErrorBoundary (http://localhost:3200/swagger-ui-bundle.js:41381:5)
    at WithErrorBoundary (http://localhost:3200/swagger-ui-bundle.js:41546:3)
    at WithSystem (http://localhost:3200/swagger-ui-bundle.js:43768:3)
    at ConnectFunction (http://localhost:3200/swagger-ui-bundle.js:116381:103)
    at Provider (http://localhost:3200/swagger-ui-bundle.js:116091:3)
    at WithRoot (http://localhost:3200/swagger-ui-bundle.js:43780:3)
printWarning @ react-dom.development.js:67
error @ react-dom.development.js:43
warnOnHookMismatchInDev @ react-dom.development.js:14897
updateHookTypesDev @ react-dom.development.js:14856
useContext @ react-dom.development.js:16388
useContext @ react.development.js:1504
useFn @ hooks.js:24
getTitle @ fn.js:14
(anonymous) @ OneOf.jsx:60
OneOf @ OneOf.jsx:57
renderWithHooks @ react-dom.development.js:14985
updateFunctionComponent @ react-dom.development.js:17356
beginWork @ react-dom.development.js:19063
beginWork$1 @ react-dom.development.js:23940
performUnitOfWork @ react-dom.development.js:22776
workLoopSync @ react-dom.development.js:22707
renderRootSync @ react-dom.development.js:22670
performSyncWorkOnRoot @ react-dom.development.js:22293
(anonymous) @ react-dom.development.js:11327
unstable_runWithPriority @ scheduler.development.js:468
runWithPriority$1 @ react-dom.development.js:11276
flushSyncCallbackQueueImpl @ react-dom.development.js:11322
flushSyncCallbackQueue @ react-dom.development.js:11309
discreteUpdates$1 @ react-dom.development.js:22420
discreteUpdates @ react-dom.development.js:3756
dispatchDiscreteEvent @ react-dom.development.js:5889
```

Example Swagger/OpenAPI definition:
```yaml
openapi: 3.1.0
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: This is a sample Pet Store Server based on the OpenAPI 3.0 specification.
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://petstore3.swagger.io/api/v3
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
              discriminator:
                propertyName: pet_type
      responses:
        '200':
          description: Updated
components:
  schemas:
    Pet:
      type: object
      required:
        - pet_type
      properties:
        pet_type:
          type: string
      discriminator:
        propertyName: pet_type
    Dog:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            bark:
              type: boolean
            breed:
              type: string
              enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:
      allOf:
        - $ref: '#/components/schemas/Pet'
        - type: object
          properties:
            hunts:
              type: boolean
            age:
              type: integer
  securitySchemes:
    petstore_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            write:pets: modify pets in your account
            read:pets: read your pets
    api_key:
      type: apiKey
      name: api_key
      in: header
```

Swagger-UI configuration options:  
Use default config in dev-helper-initializer.js (only use a local openapi contract)
```js
SwaggerUIBundle({
    url: "./swagger-config.yaml",
    dom_id: "#swagger-ui",
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    // requestSnippetsEnabled: true,
    layout: "StandaloneLayout"
  })
```

### Describe the bug you're encountering
Page is displayed properly but there is an error in browser console:  
`Warning: React has detected a change in the order of Hooks called by OneOf. This will lead to bugs and errors if not fixed`

### To reproduce...

1. git clone https://github.com/swagger-api/swagger-ui.git
2. create local file containing openapi contract with oneOf/anyOf
3. change url to load contract in dev-helpers/dev-helper-initializer.js
4. npm run dev
5. Open http://localhost:3200/
6. Open browser dev tools window
7. Expand operation containing oneOf/anyOf, display model and expand oneOf/anyOf
   => error is displayed in console

### Expected behavior
No error should be displayed in console

### Screenshots
Error occurred when clicking to expand oneOf
![image](https://github.com/swagger-api/swagger-ui/assets/21055755/b1febd4d-4877-43ea-ac97-355668b841fc)
![image](https://github.com/swagger-api/swagger-ui/assets/21055755/2733f5cf-11cb-4d9a-aa5f-d86a50b48131)

### Additional context or thoughts
Error not occurred with contract 3.0.x

**Comment by robert-hebel-sb** [comment]
We are doing some housekeeping on our issue tracker. This issue has been inactive for over a year and we have not been able to tackle it yet.

Is this still important to you? If so, please leave a comment – we'd love to know if you're still affected. If we don't hear back in 7 days, we'll close this issue to tidy up the tracker.

Thank you for your understanding!

**Comment by robert-hebel-sb** [comment]
No response received after 7 days. Closing this issue to keep the tracker tidy. If you're still affected, please reopen or create a new issue with updated details.
