### ISSUE TITLE
Cannot install on mac (npm or pnpm)

### ISSUE THREAD

**Issue by turbobuilt** [swagger-api/swagger-ui#9477]
Can't install with npm (or pnpm).  Tried with bun, and found it's having a problem with tree-sitter-yaml package.  

macos:
verbose Darwin 22.4.0
verbose node v20.5.0
verbose npm  v9.8.0

npm error

131 verbose stack TypeError: Cannot  read properties of null (reading 'matches')
131 verbose stack     at Link.matches (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1115:41)
131 verbose stack     at Link.canDedupe (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1069:15)
131 verbose stack     at PlaceDep.pruneDedupable (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:426:14)
131 verbose stack     at new PlaceDep (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:278:14)
131 verbose stack     at #buildDepStep (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:933:18)
131 verbose stack     at async Arborist.buildIdealTree (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
131 verbose stack     at async Promise.all (index 1)
131 verbose stack     at async Arborist.reify (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
131 verbose stack     at async Install.exec (/opt/homebrew/lib/node_modules/npm/lib/commands/install.js:149:5)
131 verbose stack     at async module.exports (/opt/homebrew/lib/node_modules/npm/lib/cli-entry.js:61:5)
132 verbose cwd /Users/dev/prg/noisedestroyer/api-docs
133 verbose Darwin 22.4.0
134 verbose node v20.5.0
135 verbose npm  v9.8.0
136 error Cannot read properties of null (reading 'matches')

**Comment by turbobuilt** [comment]
solved!

```
pnpm i swagger-ui --unsafe-perm
```

don't know if this is secure 😀
