### ISSUE TITLE
Uncaught TypeError: useSyncExternalStore is not a function when using swagger-ui-react

### ISSUE THREAD

**Issue by tka2943** [swagger-api/swagger-ui#9694]
### Q&A (please complete the following information)
 - OS: macOS
 - Browser: chrome
 - Method of installation: npm
 - Swagger-UI-react version: 5.11.10

### Content & configuration

Swagger/OpenAPI definition:
```yaml
# your YAML here
```

Swagger-UI configuration options:
```js
SwaggerUI({
  // your config options here
})
```

```
?yourQueryStringConfig
```

### How can we help?

I have tried using swagger ui react version 5.11.10 in my project.

i use the following in my project
react:16.14.x
react-redux:7.2.x

When installed swagger-ui-react i get the following error:

react-redux.development.cjs:1011 Uncaught TypeError: useSyncExternalStore is not a function
    at ConnectFunction (react-redux.development.cjs:1011:28)
    at renderWithHooks (react-dom.development.js:14803:18)
    at updateFunctionComponent (react-dom.development.js:17034:20)
    at updateSimpleMemoComponent (react-dom.development.js:16972:10)
    at updateMemoComponent (react-dom.development.js:16861:14)
    at beginWork (react-dom.development.js:18682:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237:16)
    at invokeGuardedCallback (react-dom.development.js:292:31)
    at beginWork$1 (react-dom.development.js:23203:7)

**Comment by char0n** [comment]
Hi @tka2943,

Please have a look at our wiki page explaining how to use older React versions: https://github.com/swagger-api/swagger-ui/wiki/Using-older-version-of-React


React@16.4.x is not support. Supports starts at React >= 16.8.
