### ISSUE TITLE
SwaggerUI not render with Angular 13, when the build optimizer is AOT

### ISSUE THREAD

**Issue by anandjaisy** [swagger-api/swagger-ui#9830]
The Angular app is embedded in the Asp.net core application. 

When the Azure ci/cd pipeline runs the below command -

 `<Exec Command="node --max_old_space_size=16384 node_modules/@angular/cli/bin/ng build --aot --build-optimizer=true --optimization=true  --vendorChunk=true  --sourceMap=false --configuration=production --output-hashing=all" />`

The UI is not rendered. However, when I do the below command

`<Exec Command="node --max_old_space_size=16384 node_modules/@angular/cli/bin/ng build --aot=false --build-optimizer=false --optimization=false --vendorChunk=false --sourceMap=false --configuration=production --output-hashing=all" />`

The UI is rendered correctly. I can't change the above command because the Abp framework handles the cache. So I can't change to false

`"swagger-ui": "^5.15.2",`

```
ReferenceError: Must call super constructor in derived class before accessing 'this' or returning from derived constructor
    at new BM (70973.b4120c6a853870c0.js:1:876457)
    at wh (70973.b4120c6a853870c0.js:1:1404179)
    at cy (70973.b4120c6a853870c0.js:1:1425258)
    at Iy (70973.b4120c6a853870c0.js:1:1471991)
    at My (70973.b4120c6a853870c0.js:1:1459909)
    at Py (70973.b4120c6a853870c0.js:1:1459837)
    at dp (70973.b4120c6a853870c0.js:1:1459700)
    at Kh (70973.b4120c6a853870c0.js:1:1456440)
    at Ey (70973.b4120c6a853870c0.js:1:1456827)
    at xl (70973.b4120c6a853870c0.js:1:1396387)
```

![image](https://github.com/swagger-api/swagger-ui/assets/84489031/8555f11d-1a97-47de-a15d-92d9e232de70)

**Comment by barrywilks7** [comment]
@anandjaisy did you get a solution for this? Also seeing the same thing

**Comment by anandjaisy** [comment]
> @anandjaisy did you get a solution for this? Also seeing the same thing

No I haven't
